### ISSUE TITLE
To be checked in SimulationUI dev

### ISSUE THREAD

**Issue by antonelepfl** [cnr-ibf-pa/hbp-bsp-issues#231]
Please check this issues that I have fixed before I can merge it to master
- [x] Simulation details does not reload after redirection from job creation (after click Show Job)
- [x] Plot of the traces (Voltage Trace Plot) is now available
- [x] When selecting to run Voltage Trace Plot the reports dropdown should show all the reports that you checked for simulation
- [x] In list of simulations, if you change the computer before all the jobs are loaded, this latest choice of computer is not picked up and you see the list of the previous computer
- [x] Analysis Target selector is cleared every time that we change a param in the analysis form.
- [x] Parameters in the analysis form are not consider (plots always showing the same amount of Cells even if we change, the same with the Target)
- [x] Jobs are not running in JURECA
- [x] Analysis plots should be downloadable
- [x] Autoreload the analysis that are QUEUED in Simulation Details
- [x] [The simulation list shows a green checkbox for analysis even if it failed](https://github.com/cnr-ibf-pa/hbp-bsp-issues/issues/228)
- [x] [Id of the job is truncated](https://github.com/cnr-ibf-pa/hbp-bsp-issues/issues/227)
- [x] [Unicore logs of analysis](https://github.com/cnr-ibf-pa/hbp-bsp-issues/issues/226)
- [x] Analysis with empty Target should not be run
- [x] When creating a simulation, clicking on the target (right part next to images) is not added in the form when it opens

**Comment by alex4200** [comment]
@antonelepfl : 
- Unable to test any anaysis again, does not seem to work. 
- JURECA jobs not running

**Comment by alex4200** [comment]
@antonelepfl : What is the maximum number of cells with which to create the traces plots?

**Comment by alex4200** [comment]
@antonelepfl : I am still not able to create a working simulation with two targets. What parameters can I use to create such a simulation?

**Comment by mmigliore** [comment]
Please restrict the tests to a single target slice.
I think that, at  this stage of the model, two targets require the  
implementation of the full model.
I strongly suggest NOT to test too often this option, since it  
requires a lot of computing time that would be better used for  
debugging the model itself, rather than testing the use case itself.
Eventually we may decide to disable this option until after the review.


alex4200 <notifications@github.com> ha scritto:

**Comment by jdcourcol** [comment]
@alex4200 please check it

**Comment by alex4200** [comment]
All points fixed...
