### ISSUE TITLE
Update validation use cases (model registering issue)

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#321]
## Summary

Aspect | Detail
------------ | -------------
Summary | Will manage duplication of model entries
Usecase Group | Validation
State | Update
Expert | Shailesh
User | All
Deadline | M12 (March 2019)
Target audience | All
Target interface | Notebook
HPC Requirements | None
Dependencies | None
Nominal runtime | Highly variable depending on usecase/test/model (typical cases < 1h)

## List of features
Update the existing validation usecases to prevent duplication of model catalog entries. Features/purpose remains same as before.

### Tasks
 
- [ ] Requires completion of #85 
- [x] Prevent duplication of entries in model catalog
- [x] Update UseCases to work with latest releases of packages

## Acceptance Criteria
- [ ] Check if all the validations use cases are working
- [ ] Confirm that no duplicate model catalog entries are created for the same model

### System
None at the moment.

### Performance
None defined. Highly variable depending on usecase/test/model (typical cases < 1h)

**Comment by appukuttan-shailesh** [comment]
As this isn't too urgent, we have decided to attend to this after we complete the switch to KnowledgeGraph. The current milestone (M12) seems appropriate.

**Comment by alex4200** [comment]
Requires completion of #85  first.

**Comment by alex4200** [comment]
Will be started in 2019

**Comment by appukuttan-shailesh** [comment]
Resolves model duplication in UseCases via fix in #428
