### ISSUE TITLE
Subcellular experiment builder

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#327]
## Summary
  
Aspect | Detail
------------ | -------------
Summary | The subcellular experiment builder is a new web application that will configure a subcellular simulation (selection of synapse, protein, reaction…) and launch a job on a super computer using the STEPS simulator and then viewing analysis result
Usecase Group | Subcellular
State | New
Expert | @jdcourcol Dan Keller
Scientific User | Robert Lindroos
Deadline | Feb 2019
Target audience | BBP, HBP, general scientists
Target interface | GUI
HPC Requirements | not now
Dependencies | bionetgen, pysb, Openshift
Nominal runtime | 5 minutes
  
## List of features

A user can create a model, either by using one of a public/private model, import a BioNetGen model or create a model by selecting the Cell -> synapse -> proteins -> concentrations. 
The user can change all parameters, can add molecules, change reactions, add reactions etc

3 use cases will be taken into account so verify the usability of the application (for 15.1.2019).

### Tasks
 
(- [ ] Define sizes for structures)
(- [ ] Implement geometry)
- [x] Implement Import feature
- [x] Implement Simulation feature
- [x] Implement graphical output feature(?)
- [ ] Implement the public/private/shared spaces.
- [ ] Change the frontend to edit values directly
- [x] Implement other simulators
- [x] handle new sessions for long-running simulations. Database for now, Nexus maybe later
- [x] Implement a viewer
- [x] Export to steps
  
## Acceptance Criteria

* A user can load a predefined model and run it
* A user can select a neuron -> synapse -> proteins -> concentrations and run the model
* A user can import and export a model (in BioNetGen format)
* A user can select models from public and shared places, but not from private or unshared places.
* All values for the parameters can be edited 'inline'.
* A user can select different simulators.
* A user can view the model
  
### System
*Does this use case require any special system requirements (any special software package)? Does this use case require HPC access? If so, which ones? List detailed system requirements here.*
  
### Performance
*What are additional performance requirements for this use case? What time should it take to run from start to end?*

**Comment by alex4200** [comment]
The basic features are implemented; to be clarified:

- [x] some inconsistencies in the test cases (expected vs. actual results)
- [x] documentation in guidebook still missing
- [x] Test of Molecular Repository

**Comment by alex4200** [comment]
All tasks finished, closing ticket
