### ISSUE TITLE
Service account for MOOCs/Web App/JupyterN

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#333]
## New Use Case
  
Aspect | Detail
------------ | -------------
Summary |  Implementation of the service needed to use a CSCS Service account and an NSG Umbrella user in order for a non member user to run the jobs/modules needed for the MOOCs/Web Apps/JupyterN on remote systems (i.e. cscs/nsg).
Group | Type: REST API service
Expert | @lbologna 
Deadline | Expected date of first release: TBD. A rough estimate at the moment is M7 (next HBP Summit)
HPC Requirements |
Dependencies |

  
## List of features

- User (e.g. a student) can open the notebook from the MOOC
- The user can configure a job to be run
- The user can simple press 'Submit' for the job to be run, without worrying about the used HPV system

The submission will go to an intermediate layer which will store data into a database (job id, name, etc), and reply the information either on the different clusters API, or though unicore. For the use case in question one service will be used through a slightly different API. 

Current quotas for individual user (per project) are:

- 5000 hours
- 10 GB (disk space)
- (these can be changed if needed)

### Tasks
 
- [x] Service Accounts for PizDaint
- [x] Set Job
- [x] Get data
- [x] Check job
- [x] Query database (with some specific queries), seperate notebook
- [x] Move to production server
- [x] Change Synaptic events fitting use case
- [x] Create documentation

## Acceptance Criteria
- Several persons can submit a job and retrieve the results
- Database query also can be done (user and admin)
- Data are visible from the database

  
### System
HPC Access:
- NSG
- CSCS
- Unicore
  
### Performance
*What are additional performance requirements for this use case? What time should it take to run from start to end?*

**Comment by lbologna** [comment]
First version of remote job launching is working on local dev.
Next tasks: test with a real world case - add security checks through hbp token validation

**Comment by alex4200** [comment]
@lbologna  Demo version for summit ready.

**Comment by lbologna** [comment]
A demo version is ready to be tested with NSG at this collab:
https://collab.humanbrainproject.eu/#/collab/17259/nav/177792

At the moment the quota/user has to be inserted manually.
@alex4200 we are granting you a quota (and access to the collab) for test purposes

=========================

We discussed with Bernd the possibility to interface the  service accounts with UNICORE (thanks to a UNICORE extension) so as to have only one entry point (i.e. UNICORE) for all HPC systems.
If feasibility is confirmed the extension should be ready by mid/end of November and the first complete version ready for testing by December.

**Comment by alex4200** [comment]
@lbologna I don't seem to have access to that page...

**Comment by lbologna** [comment]
Access granted!

Please refer to this Jupyter notebooks for testing the REST API call:
https://collab.humanbrainproject.eu/#/collab/17259/nav/206187
https://collab.humanbrainproject.eu/#/collab/17259/nav/206186

this notebook:
https://collab.humanbrainproject.eu/#/collab/17259/nav/177792
is for admin operations like inserting new projects, etc.

**Comment by alex4200** [comment]
@lbologna: I have used the "Service Accounts" notebooks and successfully started a simulation and downloaded the results to the Collab storage. At this level the Service Accounts do seem to work...

**Comment by alex4200** [comment]
At the codejam we talked about the setup and came up with the following picture:

![serviceaccounts](https://user-images.githubusercontent.com/12729291/49291273-04fb5d00-f4aa-11e8-8f44-710d8b68bf24.png)

The idea is to have a user submit something to the "Service Account" where it is either forwarded  to NSG of unicore (and then to e.g. PizDaint). This is transparent for the user and the user can check the status of her/his job and download the results. 

The Service-Account layer will log all access requests and the requested time, and will check if the quota on the system is enough. More details will follow..

**Comment by jdcourcol** [comment]
why the nsg cannot be just another unicore TSI ? with the TSI taking care of invoking the service account ?
That way there is only 1 external API that is Unicore and this is transparent to the end user.

**Comment by jdcourcol** [comment]
With respect to the on going implementation, is there an API somewhere ?

**Comment by alex4200** [comment]
@rcsm17 will update a link here to a github repo with all the documentation by end of January 2019.

**Comment by lbologna** [comment]
Current quotas for individual user (per project) are:
- 5000 hours
- 10 GB (disk space)
(these can be changed if needed)

First tests with NSG and Pizdaint availability and first draft of documentation postponed to 11/02 

**Update 2020-01-31**
The resource dedicated to the service account are 9000 node/hours and 30 GB for the entire project

**Comment by lbologna** [comment]
Two test jupyter notebooks are ready to test the job submission and result fetching through the service account API on cscs-pizdaint and nsg.

@alex4200 could you please test the following?

1) CSCS-Pizdaint: 
https://collab.humanbrainproject.eu/#/collab/17259/nav/285712
The jupyter is based on the Rebuild Single HippoCell use case so the example model file is already present in the storage. 
Check the simulation with the appropriate button until successful, so that the results are downloaded.
Then you can run the following to visualize the results:
https://collab.humanbrainproject.eu/#/collab/17259/nav/285711

2) NSG:
https://collab.humanbrainproject.eu/#/collab/17259/nav/284396
For a quick test please select the first file and the "demo" in the configuration, as shown in the figures below. 
In order to visualize the results you can then run the following:
https://collab.humanbrainproject.eu/#/collab/17259/nav/284395

Thank you!

![nsg_test_file](https://user-images.githubusercontent.com/9949990/52940537-1d6f6b00-3367-11e9-8194-230b9e00b5a8.png)

![nsg_test_config](https://user-images.githubusercontent.com/9949990/52940536-1cd6d480-3367-11e9-8912-fad33e986248.png)

**Comment by alex4200** [comment]
The tests with the notebooks and the usage of the service accounts has been done successfully. 

It remains to be tested that the backend functions work correctly (quota, users etc)

**Comment by lbologna** [comment]
@alex4200 please find here the jupyter notebook with extensive tests.
https://collab.humanbrainproject.eu/#/collab/17259/nav/301898

At the moment two hpc are available (pizdaint and nsg) with one project each. Some of the responses may be verbose at the moment, but the response code indicates the status (e.g. 404 if the job/user does not exist). Failing in submission may depend on the actual status of the hpc but after retrying it generally worked for me.

Thank you.

**Comment by lbologna** [comment]
Service Account has been moved to production on cineca vm
The jupyter notebooks "Synaptic events fitting" and "Synaptic events fitting with analysis" (in the Trace Analysis Use Case group) have been updated with the Service Account option and are ready to be moved to production.

The documentation is being finalized and will be published this week, with a link in the BSP Guidebook

**Comment by lbologna** [comment]
Service Account code is online at this link:
https://github.com/HumanBrainProject/hbp-bsp-service-account

The documentation has been published at this link:
https://humanbrainproject.github.io/hbp-bsp-service-account/

A link to the documentation page with a brief introduction to the service has been inserted in the BSP Guidebook:
https://collab.humanbrainproject.eu/#/collab/1655/nav/18580

**Comment by antonelepfl** [comment]
Hi @lbologna , can you update this https://github.com/cnr-ibf-pa/hbp-bsp-issues/issues/333#issuecomment-460200118 with the real resources that we have available?
We would like to know this because we are planning to launch a MOOC using this service account and we need to know the limitations.

**Comment by lbologna** [comment]
Hello @antonelepfl, I updated the quotas concerning the entire cscs project.
We are probably going to reduce both the time and storage quotas for individual users (@rcsm17  is working on finalizing the storage quotas which is not implemented yet).

Do you have an estimate of how much time and space a mooc process for a single user would require and how many students do you think will execute them? This is needed in order to manage the quotas at best.

Thanks.
