### ISSUE TITLE
Real-time Online status for available HPC systems.

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#344]
## New Use Case
  
Aspect | Detail
------------ | -------------
Summary | Provide an interface on top of each HPC use case to see at a glance which of the HPC systems are currently available, as well as projects' overall and users' quotas and remaining resources
Expert | @lbologna, @rcsm17 
Scientific User | This is mostly intended for final users and developers.
Timeline | Start in Feb 2019, after #333 is done; deadline exp.   March 2019. Update 4.4.2019: Start expected May 2019
Target audience |Developers and technical people to see an overview of the available HPC systems and use the modular code in their tools/services as well as final users who will refer to the HPC system status to take a decision on following actions (e.g. which system to use to launch a job)
Target interface | Frontend to be integrated in webapp + python code to be integrated in jupyter notebooks
HPC Requirements | All of them (NSG, CSCS, Juelich, Unicore,...)
Dependencies | see #333 
Nominal runtime | Dependent on authentication and HPC API response time (should be close to real time)
Link | https://bspg.pa.ibf.cnr.it:14786/#
  
## List of features
- Status on top of every notebook and GUI use case (which involves HPC)
- Indication of available systems (green) and systems offline/not reachable.
- Overall quotas and remaining resources for projects on HPC systems
- Users' quotas and remaining resources for projects on HPC systems

### Tasks
- [ ] Figure out how to do it, as the HPC query (running a complete test job) will take too log for a user. Probably update a file with regular running test jobs.
- [ ] Build a module to query HPCs overall information (e.g. system up/down, remaining resources, etc)
- [ ] Build a module to query users' resources available on HPCs systems
- [ ] Build a modular front-end code to be integrated in web apps (for GUI)
- [ ] Build a modular python code to be integrated in jupyter notebooks
  
## Acceptance Criteria
HPCs overall and user dependent status is correctly displayed

**Comment by jdcourcol** [comment]
There is already this page for the status of the HPC systems: https://collab.humanbrainproject.eu/#/collab/264/nav/4307

May be you want to implement something more BSP specific ? like the BSP projects that can be run at a particular location (cerebellum, hippocampus..) and the remaining compute time ?

**Comment by alex4200** [comment]
@lbologna Maybe a status page can also show 
- if the user has access
- if the user still has quota on the system to run something

**Comment by mmigliore** [comment]
Yes, it must be something integrated into the use cases so that the user
will know which HPC system, among those normally available, are online or
not.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by alex4200** [comment]
@lbologna Create a mockup of the expected user interface.

**Comment by alex4200** [comment]
see also https://gitlab.humanbrainproject.org/joint_infrastructure_coordination/Coordination/issues/80

**Comment by lbologna** [comment]
Here's a first mock-up of the frontend panel.
The top panel is general for all the hpc systems, while the bottom panel  opens when  a system is selected (in the mock-up, pizdaint) and displays user's specific details.
The first html version is being finalized.
Comments/suggestions? 
Thanks

<img width="600" alt="mockup_HPC_system_monitor" src="https://user-images.githubusercontent.com/9949990/59981877-5d42a980-960a-11e9-9eb1-ab3718ff39b3.png">

**Comment by mmigliore** [comment]
In general it looks ok.
Once we have a first real case implemented I will have more comments on the
bottom panel.
-M

**Comment by alex4200** [comment]
From a usability standpoint I also agree it looks fine (clear and direct information without distracting elements). 

I also need an interactive (mock) version of the html version. How does the user opens the bottom panel (clicking on the system)? Are there tooltips for the parameters (like 'Status', 'Service Account')? What will be displayed during the update of the information?  etc.

**Comment by lbologna** [comment]
Hello,

here is a first draft of the dynamic page.

https://bspg.pa.ibf.cnr.it:14786/

(the page will not be available tomorrow 08/07/2019)

Data are randomly generated at the moment but we checked with @clupascu that the API for querying  the total time remaining on Marconi and Jureca work. We will integrate them by the end of this week.

**Comment by alex4200** [comment]
@lbologna: I checked that link and it seems to work. 

I assume it still shows fake data?

**Comment by lbologna** [comment]
@alex4200 yes this are still random data
@rcsm17 is finalizing the plotting of the quotas for jsc and cineca systems

**Comment by alex4200** [comment]
Working implementation of the interface: https://bspg.pa.ibf.cnr.it:14786/#

Please all give it a try and let Luca know of any issues. (Marconi might still have some issues, but the other systems should work).

**Comment by lbologna** [comment]
Hello,

we are currently experiencing what seems to be a problem with the Marconi TSI, in that the returned RemainingComputeTime is -1, regardless of the user.
We are in contact with Michele Carpenè from Cineca to solve the issue.

**Comment by rcsm17** [comment]
The last version can be reached to: [https://bspmonitors.cineca.it](https://bspmonitors.cineca.it)
Let me know if you encounter any bug.

**Comment by mmigliore** [comment]
I tested it (from my account, I think) and:

- Jureca, OK
- Marconi, give the right total quota but no project name; in my case there
should be two projects each one with its own quota.
Also, it is not possible to check "Submission Enabled"
- Piz Daint, only the service account is shown, not the other active
projects I have there.
-NSG, OK

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by szkali** [comment]
My colleagues and I get no user-specific information (see screenshot). Is this the expected behavior?
![Screenshot from 2019-10-14 13-18-36](https://user-images.githubusercontent.com/5347908/66748871-97b9a600-ee88-11e9-9409-76fd22e10aba.png)

**Comment by rcsm17** [comment]
> My colleagues and I get no user-specific information (see screenshot). Is this the expected behavior?
> ![Screenshot from 2019-10-14 13-18-36](https://user-images.githubusercontent.com/5347908/66748871-97b9a600-ee88-11e9-9409-76fd22e10aba.png)

Sorry for the late reply.

The monitor should show your project on the HPC system with the relative quota if available. You can also check if the project is ready for the job submission by clicking on the "submission enabled" button.   
In details, the monitor check your hbp identity and show the HPCs status.
When you select one HPC, the monitor check if your account is mapped to the relative HPC and then show your projects and quotas.  

For the Service Account, the flow is different and you should see at least the SA projects of the HPC selected even if you are not mapped on the HPC.

With the correct behavior you should see something like this:
![Screenshot from 2019-11-16 13-03-19](https://user-images.githubusercontent.com/44343476/68992866-96a5db00-0871-11ea-9f6a-ded4b9dfdfe4.png)

**Comment by lbologna** [comment]
> My colleagues and I get no user-specific information (see screenshot). Is this the expected behavior?
> ![Screenshot from 2019-10-14 13-18-36](https://user-images.githubusercontent.com/5347908/66748871-97b9a600-ee88-11e9-9409-76fd22e10aba.png)

Hello @szkali,

in the most recent version of the monitor some issues have been fixed and the behavior should be the one described in the previous comment by @rcsm17 .
Could you and your colleagues please test again now at the following link and give us your feedback:
https://bspmonitors.cineca.it/

Thank you!

**Comment by szkali** [comment]
Hi @lbologna and @rcsm17 ,
There is not much change for any of us here - we still do not get any user-specific information (see screenshot).
![HPC_monitor_screenshot_20191118](https://user-images.githubusercontent.com/5347908/69054427-d0aae480-0a0b-11ea-90ab-4e9117745749.PNG)
I do get a popup message along the lines of "This user has no credential on ..."
How is the monitor supposed to know about what HPC accounts I have, and what projects are associated with them?
And what determines whether I see the service accounts?
Thanks,
Szabolcs

**Comment by lbologna** [comment]
Hello @szkali,

the monitor uses the token that is generated at login time to query the hpc systems. If the HBP user (for which the token has been generated) is mapped onto the hpc system she/he will get the sum of the quotas of her/his projects (in a short time, with the next UNICORE release, it will be possible to have the quotas for individual projects).
As for the service account, the user gets the quota of the DAINT and NSG service accounts allocated to her/him. If the user has never tried to submit a job through the service accounts, the quota is allocated at the HPC monitor request time.

@rcsm17 just fixed some minor issues. Could you please test again and tell us if the problem still persists?
Thank you.

**Comment by szkali** [comment]
There is indeed some improvement, but the results are not consistent for all users.
All of us can now see the service account on Piz Daint, and one of my colleagues can also see his project quota on the same machine. On the other hand, another colleague (@sasaray ) cannot see her project quota on Piz Daint (and gets the message "This user has no credential on PIZDAINT").
In addition, we never get any information on Jureca or NSG (they are always marked as unavailable).

**Comment by lbologna** [comment]
Hello @szkali, @sasaray,

I see. To double check, could you please clone the jupyter notebook available at the link below and tell us if you get the same results, please?

https://collab.humanbrainproject.eu/#/collab/9130/nav/287784

Systems can be temporarily unavailable but now Jureca and NSG are online so you should see at least the green icon on the HPC status for them.
As for the quotas, are you able to submit jobs to the systems for which the "... no credentials ..." message is diplayed via UNICORE? Because we are also using UNICORE to get the quotas and this discrepancy should be investigated in more details if persistent.
Thanks for your feedback.

**Comment by alex4200** [comment]
Closing ticket as the HPC-Online-status-page is available in the BSP
 production here: https://collab.humanbrainproject.eu/#/collab/1655/nav/490056
