### ISSUE TITLE
Implementing automated tests of HPC access

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#356]
Update use case

## Use Case Update
 
Aspect | Detail
------------ | -------------
Summary | Implementing automated tests which access HPC systems
Expert | @alex4200 
Deadline | 15.1.2019
Dependencies | NSG, JURECA, MACRONI  
 
## List of additional/changed features 

Currently, the automated testing suite only runs the notebook use cases just to make sure that the notebooks itself work fine. The tests do not really access HPC systems. The idea is now to check the HPC access for the different systems (NSG, JURECA, MACRONI) using the Synaptic Events Fitting use case. 

The HPC tests will contain a full test for each of the systems NSG, JURECA and MARCONI. It starts the simulation, waits for completion, downloads the results and analyzes them.
These tests will only run once a week. 

### Tasks

- [x] Clarify the type of test
- [x] Clarify how to implement the test
- [x] Implement the Fetch test for NSG
- [x] Implement the Fetch test for Unicore (JURECA)
- [x] Implement the Fetch test for MARCONI
- [x] Make sure the test works weekly
- [x] @clupascu  is working on notebook that could be used for checks (dummy job submission, accounts, quota etc.)

## Acceptance Criteria

- Tests running on a timely basis (e.g. weekly)
 
### System
- NSG
- JURECA
- MACRONI
 
### Performance
- Depends on the type. A full test of the pipeline can take hours (submitting the job, waiting queue, running job, retrieving results), while just requesting a status can finish in minutes.

**Comment by alex4200** [comment]
@clupascu is developing a notebook to test connections to the HPC systems with some extra features. The idea is to implement this notebook into the daily tests. 

Weekly tests: A full Synaptic-Events-Fitting workflow (for each HPC) with job submission and result retrieving.

**Comment by clupascu** [comment]
A new notebook for testing HPC access on Jureca, Marconi, PizDaint and NSG is available here https://collab.humanbrainproject.eu/#/collab/9130/nav/287784
The notebook contains also a GUI. The tester can insert in the first cell of the notebook the project he/she wants to use on Marconi and the username and password for NSG or he can run all cells and insert the required information in the GUI.

In the third tab of the GUI the tester can see what is the status of the HPC system. In the fourth tab he/she can run a quick job and fetch the results that are visualized in a text area widget. In the fifth tab the tester can query the current quota status on the HPC system (only Jureca is available for now).

I think this notebook includes fetch tests for Jureca and Marconi too, so we should check those tasks too. @alex4200 please make sure the tests are working. Thanks.

**Comment by alex4200** [comment]
Tests need just be pushed to production.

**Comment by alex4200** [comment]
Tests are implemented.
