### ISSUE TITLE
Replacing the header uniformly of all notebook use cases

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#370]
Update use case

## Use Case Update
 
Aspect | Detail
------------ | -------------
Summary | Replacing the header information for all use cases that use a notebook to ensure uniformity across the use cases. 
Expert | @alex4200 
Deadline | 31.1.2019
Dependencies | none
 
## List of additional/changed features 

* Have uniform headers across the use cases
* Different headers for GUI notebooks (Carmen's use cases) and the other ones.
* Have the header shorter, with a note to the native help.

```
 ## Using this notebook
 
- You have to execute "Run All cells" everytime you open this notebook.
- If you logout and want to keep any changes made, you need to save the notebook. 

For detailed information about the notebook interface see `Help ->  User Interface Tour` in the menu.
```

```
 ## Using this notebook
 
- You have to execute this notebook by running each cell consecutive.
- If you logout and want to keep any changes made, you need to save the notebook. 

For detailed information about the notebook interface see `Help ->  User Interface Tour` in the menu.
```

Guidebook text:

Guidebook not changed, using native interactive help

### Tasks

- [x] Define header text for GUI-notebook
- [x] Define header text for non-GUI notebooks
- [ ] Change the header text in the use cases

## Acceptance Criteria
* Each notebook has a new header in the same style.

**Comment by alex4200** [comment]
@Carmen waiting for feedback from @mmigliore

**Comment by mmigliore** [comment]
what about something like this

## Using this notebook
- "Run All cells" must be executed every time you open this notebook.
- To keep any changes, remember to save the notebook before leaving
the notebook.

For more detailed information please see the Guidebook at
(https://lbologna.github.io/hbp-sp6-guidebook/getting_started/getting_started.html#working-with-collabs)

Michele

**Comment by mmigliore** [comment]
Hi Alex,
let's talk about this later today. I do not see any "Help --> User
Interface Tour" in the menu.
Michele

**Comment by alex4200** [comment]
Latest version

```
 ## Using this notebook
 
- You have to execute this notebook by running each cell consecutively.
- To retain any changes made, you need to save the notebook. 

For detailed information about the notebook interface see _Help -> User Interface Tour_ in the menu, and the [Guidebook](https://lbologna.github.io/hbp-sp6-guidebook/getting_started/getting_started.html#working-with-collabs) for working with Collabs.
```

**Comment by alex4200** [comment]
Followup ticket: #382
