### ISSUE TITLE
LFP computation on HPC systems

### ISSUE THREAD

**Issue by ElisabettaGiacalone** [cnr-ibf-pa/hbp-bsp-issues#375]
## Use Case Update
 
Aspect | Detail
------------ | -------------
Summary | LFP computation on HPC systems (Cineca ,Juelich, CSCS) in addition to BBP system
Expert | @pramodk 
Deadline | TBD
Dependencies | HPC
 
**Remove anything that does not apply**
## List of additional/changed features 
The new feature will allow to run the following code on the above mentioned HPC systems:

module purge
module load nix/viz/emsim
emsim -i /gpfs/bbp.cscs.ch/project/proj42/home/giacalon/w1syn01/BlueConfig --target sliceb2 --report AllCompartmentsMembrane --voxel-size 1,1,1 --start-time 200 --end-time 1500 --output=sliceb2_9 \
--sample-point 2494.5,5725.4,5976.8 

### Tasks

- [x] LFP computation on Juelich
- [x] LFP computation on CSCS
- [x] LFP computation on Cineca

## Acceptance Criteria
* LFP computation on Cineca, Juelich, CSCS systems

**Comment by pramodk** [comment]
@ppodhajski : From simulation side we are deploying all stack via Spack. As this package is only with nix, could you have a look at this?

**Comment by ppodhajski** [comment]
Yes, I will have a look,. In the team we had some discussion on Spack, so maybe it is a good opportunity to test if Spack works for viz team.

**Comment by jdcourcol** [comment]
@ppodhajski Please deploy with nix first. I think Spack investigation can take a long time and I would avoid to have that in the critical path.

**Comment by alex4200** [comment]
@ElisabettaGiacalone Please see related ticket #154

**Comment by jdcourcol** [comment]
@alex4200 can we have @ppodhajski assigned to that one instead ?
did he accept the invite ?

**Comment by alex4200** [comment]
Hi,


I am still awaiting for @ppodhajski<https://github.com/ppodhajski> and Pablo Serna to accept the invitation. Should I contact them about that, or can you do that?<https://g>


Alex

________________________________

**Comment by ppodhajski** [comment]
accepted

**Comment by alex4200** [comment]
@ppodhajski Is there any news regarding this issue?

**Comment by ppodhajski** [comment]
with help of Tristan I installed nix on jurecavis (via spack), as it had to be reinstalled after introducing new usage model at JSC. Currently trying to fix the issue when building with nix. 

The problem encountered:
patching /p/project/cvsk25/bbp-viz-deployment/HBP/jurecavis/nix/store/aa8kd6z12mj69yx89m8km66ccs7cdli6-bootstrap-tools/bin/[
stat: Value too large for defined data type

**Comment by ppodhajski** [comment]
@ElisabettaGiacalone  please try executing:
/p/project/cvsk25/bbp-viz-deployment/HBP/jurecavis/appimage/emsim/AppRun

**Comment by ElisabettaGiacalone** [comment]
@ppodhajski  I get "permission denied" to access to emsim folder

**Comment by ppodhajski** [comment]
@ElisabettaGiacalone  please retry

**Comment by ElisabettaGiacalone** [comment]
@ppodhajski 
Now I  can access to emsim folder, but when I execute 
/p/project/cvsk25/bbp-viz-deployment/HBP/jurecavis/appimage/emsim/AppRun
I get:
/p/project/cvsk25/bbp-viz-deployment/HBP/jurecavis/appimage/emsim/AppRun: line 7: /p/project/cvsk25/bbp-viz-deployment/HBP/jurecavis/appimage/emsim/bin/emsim: Permission denied

**Comment by ppodhajski** [comment]
should be good now

wt., 19 lut 2019 o 13:51 ElisabettaGiacalone <notifications@github.com>
napisał(a):

**Comment by clupascu** [comment]
I get now 
/p/project/cvsk25/bbp-viz-deployment/HBP/jurecavis/appimage/emsim/bin/emsim: error while loading shared libraries: libboost_program_options.so.1.54.0: cannot open shared object file: No such file or directory

**Comment by ppodhajski** [comment]
it is strange, I added some debug print, please try again and report
LD_LIBRARY_PATH (it will print its content).

wt., 19 lut 2019 o 13:56 clupascu <notifications@github.com> napisał(a):

**Comment by clupascu** [comment]
/p/project/cvsk25/bbp-viz-deployment/HBP/jurecavis/appimage/emsim/AppRun
LD_LIBRARY_PATH to be reported:  /p/project/cvsk25/bbp-viz-deployment/HBP/jurecavis/appimage/emsim/lib:/usr/local/software/jureca/Stages/2018b/software/binutils/2.31.1-GCCcore-7.3.0/lib:/usr/local/software/jureca/Stages/2018b/software/GCCcore/7.3.0/lib/gcc/x86_64-pc-linux-gnu/7.3.0:/usr/local/software/jureca/Stages/2018b/software/GCCcore/7.3.0/lib64:/usr/local/software/jureca/Stages/2018b/software/GCCcore/7.3.0/lib
Error: the option '--input' is required but missing

  -h [ --help ]         Print this help message.

  -i [ --input ] arg    Path to Blueconfig file.
  -o [ --output ] arg   Path for the output file.
  --target arg          The circuit's target.
  --report arg          The name of the report.
  --start-time arg      The start time
  --end-time arg        The end time
  --fraction arg        Specify the fraction [0.0 1.0] of gids to be used
                        during the computation. Default is 1.0.
  --export-volume       Will export a floating point volume for each time
                        steps.

  --voxel-size arg      The size in each dimension of a voxel in circuit units.
                        Default is 4.0,4.0,4.0. Must be written in the form:
                        --voxel-size rx,ry,rz
  --volume-extent arg   Specify an additional 3d extent for the volume in
                        micrometers. Default is 0.0,0.0,0.0. Must be written in
                        the form: --volume-extent ex,ey,ez
  --sample-point arg    The x y z positions of a sample point. Must be written
                        in the form: --sample-point x,y,z

**Comment by ppodhajski** [comment]
I modified the permissions in the meantime on library folder and it seems
to work now, right?

wt., 19 lut 2019 o 14:09 clupascu <notifications@github.com> napisał(a):

**Comment by clupascu** [comment]
it is not working

/p/project/cvsk25/bbp-viz-deployment/HBP/jurecavis/appimage/emsim/AppRun
Error: the option '--input' is required but missing

  -h [ --help ]         Print this help message.

  -i [ --input ] arg    Path to Blueconfig file.
  -o [ --output ] arg   Path for the output file.
  --target arg          The circuit's target.
  --report arg          The name of the report.
  --start-time arg      The start time
  --end-time arg        The end time
  --fraction arg        Specify the fraction [0.0 1.0] of gids to be used
                        during the computation. Default is 1.0.
  --export-volume       Will export a floating point volume for each time
                        steps.

  --voxel-size arg      The size in each dimension of a voxel in circuit units.
                        Default is 4.0,4.0,4.0. Must be written in the form:
                        --voxel-size rx,ry,rz
  --volume-extent arg   Specify an additional 3d extent for the volume in
                        micrometers. Default is 0.0,0.0,0.0. Must be written in
                        the form: --volume-extent ex,ey,ez
  --sample-point arg    The x y z positions of a sample point. Must be written
                        in the form: --sample-point x,y,z

**Comment by ppodhajski** [comment]
I am not emsim developer but this seems to be application stdout or stderr,
which means you need to specify the --input parameter. I think you need to
specify --output and --report as well.

wt., 19 lut 2019 o 14:13 clupascu <notifications@github.com> napisał(a):

**Comment by ElisabettaGiacalone** [comment]
Yes, I get the same output, but I suppose it is the output with all options of the function.
I am going to try with all the required data and I will give you a feedback.

**Comment by ElisabettaGiacalone** [comment]
Hi @ppodhajski, I tried with a test simulation output, and it works.

/p/project/cvsk25/bbp-viz-deployment/HBP/jurecavis/appimage/emsim/AppRun -i /p/scratch/cvsk25/vsk2505/test-190219/BlueConfig --target slice0 --report AllCompartmentsMembrane --voxel-size 1,1,1 --start-time 0 --end-time 300 --output=slice0 --sample-point 3740.8,2398.6,5724.4

**Comment by ElisabettaGiacalone** [comment]
@ppodhajski Would it be be possible to do the same on Cineca and CSCS systems?

**Comment by ppodhajski** [comment]
@ElisabettaGiacalone, yes I will work on that and let you know when it is in place

**Comment by ppodhajski** [comment]
@pramodk Could you please let me know the path (gpfs) where I can deploy it on Cineca?

**Comment by pramodk** [comment]
In the past Adrien was deploying stuff on Marconi in `/marconi_work/HBP_CDP2_it/nix`.

I am not sure if project (HBP_CDP2_it) is changed. @clupascu or @ElisabettaGiacalone should confirm the project directory under `/macroni_work`.

**Comment by clupascu** [comment]
The project is HBP_CDP2_it_0

**Comment by ppodhajski** [comment]
@ElisabettaGiacalone: I put Emsim here: /marconi_work/HBP_CDP2_it_0/bbp-visualisation/emsim/emsim

**Comment by alex4200** [comment]
Is there any update on this issue?

@romani79: For your information

**Comment by ElisabettaGiacalone** [comment]
I have not tested yet on Marconi with data from simulation because I want to test it on the new full scale Hippocampus model, but it seems to work.

@ppodhajski, Is there any update on the installation on CSCS ?

**Comment by ppodhajski** [comment]
@ElisabettaGiacalone I am waiting for access rights to CSCS. 
Will update the ticket then.

**Comment by alex4200** [comment]
@ppodhajski No news on this item?

**Comment by ppodhajski** [comment]
> @ppodhajski, Is there any update on the installation on CSCS ?

@ElisabettaGiacalone what path on CSCS should it be deployed?

**Comment by clupascu** [comment]
I think it can be deployed here /apps/hbp/ich002/hbp-spack-deployments/

**Comment by ppodhajski** [comment]
@clupascu @elisamarenzi please see it under  /apps/hbp/ich002/hbp-visualisation-deployements/emsim/emsim

**Comment by ElisabettaGiacalone** [comment]
@ppodhajski I have just tested that on CSCS with this code:

 /apps/hbp/ich002/hbp-visualisation-deployements/emsim/emsim -i /scratch/snx3000/bp000139/w1syn03_testLFP/BlueConfig --target slice2 --report AllCompartmentsMembrane --voxel-size 1,1,1 --start-time 200 --end-time 600 --output=slice2 --sample-point 3740.8,2398.6,5724.4

But I get this error (despite the input is specified) :

Error: the option '--input' is required but missing

  -h [ --help ]         Print this help message.

  -i [ --input ] arg    Path to Blueconfig file.
  -o [ --output ] arg   Path for the output file.
  --target arg          The circuit's target.
  --report arg          The name of the report.
  --start-time arg      The start time
  --end-time arg        The end time
  --fraction arg        Specify the fraction [0.0 1.0] of gids to be used
                        during the computation. Default is 1.0.
  --export-volume       Will export a floating point volume for each time
                        steps.

  --voxel-size arg      The size in each dimension of a voxel in circuit units.
                        Default is 4.0,4.0,4.0. Must be written in the form:
                        --voxel-size rx,ry,rz
  --volume-extent arg   Specify an additional 3d extent for the volume in
                        micrometers. Default is 0.0,0.0,0.0. Must be written in
                        the form: --volume-extent ex,ey,ez
  --sample-point arg    The x y z positions of a sample point. Must be written
                        in the form: --sample-point x,y,z

**Comment by ppodhajski** [comment]
Hi @ElisabettaGiacalone,
I am back to the office after my holidays, please try it now; there was a small permission issue

**Comment by ElisabettaGiacalone** [comment]
Hi, I just tried on CSCS and it works now. Thanks.

I am going to test it on Marconi.

**Comment by ElisabettaGiacalone** [comment]
@ppodhajski I have just tried on Marconi, but I think I have the same permission problem as before on CSCS:

[mmiglior@r000u07l02 test-31aug]$ /marconi_work/HBP_CDP2_it_0/bbp-visualisation/emsim/emsim -i /marconi_work/HBP_CDP2_it_0/hippo-mm/test-31aug/BlueConfig --target slice2 --report AllCompartmentsMembrane --voxel-size 1,1,1 --start-time 0 --end-time 300 --output=slice2 --sample-point 3740.8,2398.6,5724.4
Error: the option '--input' is required but missing

  -h [ --help ]         Print this help message.

  -i [ --input ] arg    Path to Blueconfig file.
  -o [ --output ] arg   Path for the output file.
  --target arg          The circuit's target.
  --report arg          The name of the report.
  --start-time arg      The start time
  --end-time arg        The end time
  --fraction arg        Specify the fraction [0.0 1.0] of gids to be used
                        during the computation. Default is 1.0.
  --export-volume       Will export a floating point volume for each time
                        steps.

  --voxel-size arg      The size in each dimension of a voxel in circuit units.
                        Default is 4.0,4.0,4.0. Must be written in the form:
                        --voxel-size rx,ry,rz
  --volume-extent arg   Specify an additional 3d extent for the volume in
                        micrometers. Default is 0.0,0.0,0.0. Must be written in
                        the form: --volume-extent ex,ey,ez
  --sample-point arg    The x y z positions of a sample point. Must be written
                        in the form: --sample-point x,y,z

**Comment by ppodhajski** [comment]
@ElisabettaGiacalone it is fixed now!

**Comment by ElisabettaGiacalone** [comment]
Thanks, it works now.
We can close the issue.

**Comment by antonelepfl** [comment]
Hi @ppodhajski, I would need this [fix](https://bbpteam.epfl.ch/project/issues/browse/BSD-72) deployed on PizDaint and Jureca.

**Comment by ppodhajski** [comment]
hi @antonelepfl, I am trying to deploy it via spack on piz daint but ran into some compilation issues. will keep you posted.

**Comment by antonelepfl** [comment]
Do you have any update on this?

**Comment by ppodhajski** [comment]
please try binaries in the folder below:
`/apps/hbp/ich002/hbp-visualisation-deployements/spack/softwares/28-04-2020/install/install/cray-cnl7-haswell/intel-19.0.1.144/emsim-1.0.0-vbdt6g/bin`

or built with gcc:
`/apps/hbp/ich002/hbp-visualisation-deployements/spack/softwares/28-04-2020/install/install/cray-cnl7-haswell/gcc-8.3.0/emsim-1.0.0-lewa5k/bin`

These are built with brion version 3.1.0 (https://github.com/BlueBrain/Brion/releases)

**Comment by ElisabettaGiacalone** [comment]
Hi @ppodhajski, I am trying emsim on Jureca for the first time with the new model, but I get this error:

`[giacalone1@jrl12 type_l_test]$ /p/project/cvsk25/bbp-viz-deployment/HBP/jurecavis/appimage/emsim/emsim -i BlueConfig --target slice30 --report AllCompartmentsMembrane --voxel-size 1,1,1 --start-time 0 --end-time 300 --output=slice0 --sample-point 3740.8,2398.6,5724.4              WARNING: Time range is clamped to the minimum bound.
INFO: Time range is: [300 300] with DT: 0.25
Normalized current sum: -3.43139e-09
INFO: Compartments count: 8300167
terminate called after throwing an instance of 'std::runtime_error'
  what():  Could not open morphology file /p/project/cvsk25/vsk2516/hpc/entities/morphologies/20180417//011127HP1_-_Clone_0.h5: Unable to open file /p/project/cvsk25/vsk2516/hpc/entities/morphologies/20180417//011127HP1_-_Clone_0.h5 (File accessibilty) Unable to open file
/p/project/cvsk25/bbp-viz-deployment/HBP/jurecavis/appimage/emsim/emsim: line 11: 31321 Aborted                 LC_NUMERIC=C LD_LIBRARY_PATH=${HERE}/lib:$LD_LIBRARY_PATH ${HERE}/bin/emsim "$@"
`

**Comment by ppodhajski** [comment]
Hi,
new version is deployed on piz daint only. please try with the binaries I
posted above

wt., 28 kwi 2020 o 18:34 ElisabettaGiacalone <notifications@github.com>
napisał(a):

**Comment by ElisabettaGiacalone** [comment]
@ppodhajski please, could you deploy it also on Jureca?

**Comment by antonelepfl** [comment]
Your [deployment](https://github.com/cnr-ibf-pa/hbp-bsp-issues/issues/375#issuecomment-620650316) on PizDaint works correctly. I tried both paths and they work. Which one do you recommend to use?

**Comment by ppodhajski** [comment]
I cannot download some sources on jureca:

```
[podhajski1@jrc1387 spack]$ wget https://sourceware.org/
--2020-04-29 13:28:49--  https://sourceware.org/
Resolving sourceware.org (sourceware.org)... 209.132.180.131
Connecting to sourceware.org (sourceware.org)|209.132.180.131|:443... 
```
Do you know if I there is some proxy I could use? In the meantime I created a ticket for this issue.

**Comment by ppodhajski** [comment]
> Which one do you recommend to use?

Both are fine to use.

**Comment by mmigliore** [comment]
@ppodhajski  I am not sure to understand the wget problem. 
Is it the first time that you try to get those files, or you were able to get them before and now it does not work anymore?
In any case, if you and/or @pramodk think it is a problem with the Jureca system, open a ticket by sending an email to sc@fz-juelich.de

**Comment by pramodk** [comment]
Yes, this should go to :sc@fz-juelich.de.

**Comment by ppodhajski** [comment]
In the meantime I deployed emsim with brion fixes using an AppImage. 
@ElisabettaGiacalone please validate it: 
/p/project/cvsk25/bbp-viz-deployment/HBP/jurecavis/appimage/emsim/emsim

**Comment by ElisabettaGiacalone** [comment]
@ppodhajski it works correctly, thank you!
