### ISSUE TITLE
Model Catalog uses KnowledgeGraph as database backend

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#380]
## Use Case Update
 
Aspect | Detail
------------ | -------------
Summary | Adapt the Model Catalog on the Brain Simulation Platform to use the Knowledge Graph as its database backend.
Expert | @apdavison 
Deadline | ~~Expected latest end Feb 2019~~ 15 March
Dependencies | #85 
 
## List of additional/changed features 

* When using the Model catalog, the data is used from the KnowledgeGraph. 

### Tasks

- [x] develop KG metadata schemas for model projects and model instances.
- [x] develop script to migrate model catalog from PostgreSQL to KG
- [x] adapt REST API implementation to read/write from KG instead of PostgreSQL
- [x] thoroughly test, using KG integration server ("nexus-int")
- [x] perform definitive migration to KG production server, deploy new REST API implementation in production

## Acceptance Criteria
*Nothing should change for the user; should still be able to find models.

**Comment by apdavison** [comment]
Deployment to production will be coordinated with #425, and so is delayed.

**Comment by apdavison** [comment]
I have realized that there is a permissions problem with the KG, users would need to be added to a specific group in order to view the model catalog, even public models. The solution is to use a service account, I am in contact with the KG team about this.

**Comment by appukuttan-shailesh** [comment]
Final task expected to be completed by end-Nov.

**Comment by alex4200** [comment]
Andrew will move the KG-based apps from staging to production in first week on January.

**Comment by apdavison** [comment]
Done
