### ISSUE TITLE
Notebook cloning with common Header and Versioning Control (github repo)

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#382]
Update use case

## Use Case Update
 
Aspect | Detail
------------ | -------------
Summary | Put the PROD notebooks into a github repo, and change the notebook cloning so that each notebook will contain a common header across the notebooks, and set up things so that the user is notified when a newer version of the notebook is available. DEV notebooks will be still on the Collab.
Expert | @antonelepfl 
Deadline | ~ Begin Feb 2019
Dependencies |
 
## List of additional/changed features 
 * Each cloning of a notebook should create two cells
 * A markdown cell with a common header (see #370)
 * A code cell to check if a newer version of the original notebook is available.
 * A button for a user to click on to replace the notebook with a newer version 

Common header (from ticket #370):

```
 ## Using this notebook
 
- You have to execute this notebook by running each cell consecutively.
- To retain any changes made, you need to save the notebook. 

For detailed information about the notebook interface see _Help -> User Interface Tour_ in the menu, and the [Guidebook](https://lbologna.github.io/hbp-sp6-guidebook/getting_started/getting_started.html#working-with-collabs) for working with Collabs.
```

 ## Using this notebook
 
- You have to execute this notebook by running each cell consecutively.
- To retain any changes made, you need to save the notebook. 

For detailed information about the notebook interface see _Help -> User Interface Tour_ in the menu, and the [Guidebook](https://lbologna.github.io/hbp-sp6-guidebook/getting_started/getting_started.html#working-with-collabs) for working with Collabs.

### Tasks

- [ ] Select github repo to keep the notebooks (i.e. Production notebooks in repository)
- [ ] Change the cloning mechanism so notebooks are cloned from the github repo (with the corresponding cloning SHA1 ID). 
- [ ] Implement mechanism to commit changed DEV notebooks to PROD repo: Just a simple 'git commit'
- [ ] Add metadata to the cloned notebook with (i) timestamp (in format  %Y-%m-%dT%H:%M:%S.%fZ, (ii) the ID of the DEV notebook (iii) the id of the Prod notebook
- [ ] Add the two cells to the top of the notebook with (i) the common header and (ii) the version check code (provided by @appukuttan-shailesh ). 
- [ ] The code cell contains the ID of the new created cloned notebook
- [ ] Make sure that the GUI notebooks (from @clupascu) are consistent with the new header.

## Acceptance Criteria
* New header is visible correctly
* The version check code runs
* If the cloned notebook is newer, no message appears
* If the cloned notebook is older, a message/button to replace appears
* When the user clicks the button the notebook content is replaced (and notebook is restarted)
* The metadata for the cloned notebooks are in place

**Comment by appukuttan-shailesh** [comment]
@antonelepfl : Do you have an estimate of when Task 1 (Add metadata to the cloned notebook...) would be ready?

**Comment by appukuttan-shailesh** [comment]
This versioning check will be run each time a usecase notebook is run (will be placed as the first cell.... read-only protected). User will be notified if a newer version exists, and will be given the option to update the usecase if they desire. If they opt not to update, the existing usecase (outdated) will continue to be executed.

**Comment by jdcourcol** [comment]
the source use case notebook is stored in GitHub ?

**Comment by appukuttan-shailesh** [comment]
It is stored inside a dedicated Collab storage.
(@alex4200: correct me if I am wrong)

**Comment by alex4200** [comment]
Yes, the original notebook is stored in a Collab. And we need to set a timestamp manually when a notebook is cloned, see the explanation above.

**Comment by jdcourcol** [comment]
I think we should have the original notebooks stored in GitHub. This sounds to me quite unsafe otherwise as there is no versioning in the collab storage.

**Comment by appukuttan-shailesh** [comment]
If we wish to maintain a history of the usecase development, then a versioning service such as GitHub is useful. But if the intention is just to add the extra feature of user notification for outdated notebooks, then we could continue on the Collab storage itself.

For now, the source usecases simply get updated with no version control system to allow access to older versions.

**Comment by appukuttan-shailesh** [comment]
Note: the user is never forced to update their copy of the notebook (where they might have made their own changes). They would simply be notified of the existence of a newer version, and given the option to update their notebook.

**Comment by jdcourcol** [comment]
do we actually need a timestamp ? for the time being, what is see is that you need to know that the user notebook is different from the template notebook.
so if the template has an unique id (say a uuid), then the clone should have the same when the clone is created. if the template id gets updated then, you know that you have a difference.

**Comment by appukuttan-shailesh** [comment]
As per the current workflow, the ID of the source and the cloned notebooks do not change. This is because they are not re-created, but the contents are simply updated. The advantage of this is that the URL to these notebooks do not change (once cloned into Collabs).

**Comment by antonelepfl** [comment]
@appukuttan-shailesh We should define the library that we are going to import in the header to check the version. Remember that now we should compare to the github notebook (all production notebooks will be there)

**Comment by antonelepfl** [comment]
I have created a sample notebook with the result of the elements that I'll add in the common header in [Notebook Header and Versioning](https://collab.humanbrainproject.eu/#/collab/42085/nav/296755) Collab.
Let me know if there is anything I can improve

**Comment by alex4200** [comment]
@antonelepfl I think the header is fine. But I would add one or two sentences explaining the content of the cell (as comment inside a call). Something like:

```#This cell specifies dynamic data and code to check if an updated version of this notebook is available. Do not make any changes to this cell.```

**Comment by antonelepfl** [comment]
If you can, just make a Pull Request to the [Usecases Repo](https://github.com/antonelepfl/usecases/blob/dev/production_notebooks/common_header/common_headers.ipynb) in this way we are trained how to modify that file for future changes

**Comment by appukuttan-shailesh** [comment]
Thanks @antonelepfl . I think I would be able to work on this only next week at the earliest. Will update you asap.

In addition to @alex4200's suggestion above, it would be good to make these cells read-only via the cell's metadata:
```
{
  "trusted": true,
  "editable": false,
  "deletable": false
}
```

**Comment by appukuttan-shailesh** [comment]
@antonelepfl , @alex4200 : since you both already started work on this and have a prototype under dev, I will leave the implementation to both of you. Looking forward to trying it out. Thanks for taking this up.

**Comment by alex4200** [comment]
Code repository was created at ssh://bbpcode.epfl.ch/nse/notebook-version-check

**Comment by antonelepfl** [comment]
We have deployed this in DEV and PROD so all the use cases from now on when you copy should include the header.
