### ISSUE TITLE
Documentation for Blue-NaaS

### ISSUE THREAD

**Issue by appukuttan-shailesh** [cnr-ibf-pa/hbp-bsp-issues#399]
## Details description of the task
Really good to see BlueNaaS gaining so much more functionality in the last few months. I see that we are having a lot of discussions via emails and Github on how to use these features. It is important for us to document these features so that new users can easily start employing them. E.g. the structure of the experimental "traces" file, how they should be named, the details for the synapses json file, name of URL keyword parameters for initializing parameters etc.

## Description of how to test it
See if the documentation (that would be developed / is already available?) helps users make use of the various Blue-NaaS features.

## Items updated on BlueNaaS 

**which might get into the documentation [here](https://lbologna.github.io/hbp-sp6-guidebook/online_usecases/single_cell_in_silico/single_cell_clamp/single_cell_clamp.html):**

- [ ] Temperature is new parameter (needs screenshot update), see #330 
- [ ] Neuron Version might be mentioned (#397)
- [ ] Probably does not need to be mentioned in the documentation: The Neuron error popup (#398)
- [ ] Spines/synapses being displayed (#396)
- [ ] Synaptic input? (#374)
- [ ] Handling of attached traces (#393)
- [ ] BlueNaaS is callable with a model and the parameters (#394)
- [ ] Not sure if this is the pace for the doc: The incorporation into the Model Catalog (#357)

**Comment by appukuttan-shailesh** [comment]
This ticket can be closed if such documentation already exists, but after a link/button to the documentation is provided on the Blue-NaaS page.

**Comment by genric** [comment]
Hi @appukuttan-shailesh. If you hit an icon in the upper left corner of BlueNaaS it will bring you to this help page: https://lbologna.github.io/hbp-sp6-guidebook/online_usecases/single_cell_in_silico/single_cell_clamp/single_cell_clamp.html (Which probably needs to be updated with all the recent developments, so we can keep the ticket to do that)

**Comment by genric** [comment]
Should be fixed by https://github.com/lbologna/hbp-sp6-guidebook/pull/52

**Comment by genric** [comment]
lbologna/hbp-sp6-guidebook#52 just got merged, so I guess we can close this one.
