### ISSUE TITLE
Change hippocampus model selection for simulation

### ISSUE THREAD

**Issue by jdcourcol** [cnr-ibf-pa/hbp-bsp-issues#400]
## Change request for the Simulation UI.
 
Aspect | Detail
------------ | -------------
Summary | A change to have the user select the brain region and the model in the UI of the BSP. When the actual SimUI App starts, the user cannot change the model anymore. 
Expert | @SteMasoli 
Deadline | 31.3.2019 (M12)
Dependencies | change in SimUI, change in usecases. 
 

Step 1: in the BSP UI: "please select a **brain region**" with "hippocampus" or "cerebellum"
Step 2: in the BSP UI:  "please select a model" with the following choices
 1) "Configure and run a rat hippocampus CA1 region using preconfigured HBP model and data
A circuit of detailed neuron models based on the Ascoli atlas."  ( as of today)
 2) "Configure and run a hippocampus column"
A microcircuit of detailed neuron models with a column shape.

Step 3: The actual SimUI starts here where the user **cannot** change the model anymore. 

### Tasks

- [x] Change in the BSP UI
- [x] Change in the UI
- [x] Change for the passed on parameters
- [x] Updating documentation  (see [JIRA](https://bbpteam.epfl.ch/project/issues/browse/NSETM-659))
