### ISSUE TITLE
KappaNeuron Demo notebook

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#406]
## New Use Case
  
Aspect | Detail
------------ | -------------
Summary | An example use case on how to use KappaNeuron
Usecase Group | Subcellular Group?
Expert | David C. Sterratt
Scientific User | 
Deadline | M18
Target audience | Experts
Target interface | Notebook (Example/Tutorial)
HPC Requirements | none
Dependencies | java, KappaNeuron
Nominal runtime | ~ 1 minute
  
**Remove anything that does not apply**
## List of features

- rule based modelling
- similar to BioNetGen
- staochastic simulation

**Related information:** 

- KappaNEURON repo: [KappaNEURON](https://github.com/davidcsterratt/KappaNEURON)
- Dev notebook: https://collab.humanbrainproject.eu/#/collab/2184/nav/204920
- Dev guidebook: https://github.com/davidcsterratt/hbp-sp6-guidebook/tree/KappaNEURON/source/online_usecases/complex_molecular_electrical_modelling

 
### Tasks
 
- [x] Test Notebook
- [x] Update inline documentation
- [x] Provide Guidebook documentation
- [x] Create new use case group
    
## Acceptance Criteria
* Notebook runs in the BSP for users

**Comment by davidcsterratt** [comment]
There is a simple example here:
https://collab.humanbrainproject.eu/#/collab/2184/nav/204920
It takes about a minute to run.

There is a more complex example here:
https://collab.humanbrainproject.eu/#/collab/2184/nav/303192
It takes longer to run.

In both scripts, there's quite a bit of time spent installing java (if not already installed in the user's home dir) and also transferring the files from storage. It's been suggested that this could be speeded up by storing them as a zip file and then unzipping.

KappaNEURON is in development, but the notebooks shouldn't need to be updated when I release a future version, as I deploy it using pip and pythonhosted.

**Comment by alex4200** [comment]
@davidcsterratt  If a notebook of yours is ready to be tested, let me know, and also see the instructions for adding a new notebook here:  "https://github.com/antonelepfl/usecases/"

**Comment by davidcsterratt** [comment]
I've tested both notebooks. I've had a go at updating the inline documentation for the first (the simple example): https://collab.humanbrainproject.eu/#/collab/2184/nav/204920
Is that the sort of level of detail and style that you would like?

**Comment by davidcsterratt** [comment]
I've now got a first draft of the guidebook material, in the  complex_molecular_electrical_modelling section
https://github.com/davidcsterratt/hbp-sp6-guidebook/tree/KappaNEURON
Not sure if this is the right sort of stuff, so there are still probably a good number of typos - please let me know what you think, and I can do major or minor work as required.

**Comment by alex4200** [comment]
@davidcsterratt  I compiled your branch, but I cannot find and documentation regarding 'molecular' content.

**Comment by davidcsterratt** [comment]
Hmm.. the new section is here:
https://github.com/davidcsterratt/hbp-sp6-guidebook/tree/KappaNEURON/source/online_usecases/complex_molecular_electrical_modelling

(Maybe the name of the section should be different.) It seemed to compile OK for me.

**Comment by alex4200** [comment]
@davidcsterratt Now it works;  I used the wrong branch.

For me the documentation looks fine, because if contains code examples and images. However. I would suggest to put the documentation in a new section "Subcellular Level" below "Online Use Cases" at the top of the Guidebook. Then you will find the documentation in increasing scale from "Subcellular", "Trace", "Single Cell Building", "Circuit Building" etc. I hope that makes sense. 

I will ask an expert here to look at the documentation as well.

**Comment by davidcsterratt** [comment]
I've accepted your suggestions, and tweaked the text a bit more, adding links an references to the KappaNEURON page. I've also moved it to the "Subcellular level" as suggested. All committed to the master branch of: https://github.com/davidcsterratt/hbp-sp6-guidebook

**Comment by alex4200** [comment]
@davidcsterratt Thanks for the changes. 

However, I have seen two items that needs correction:
1. The link to the "KappaNEURON use case"  must be updated once the use case is in Production. 
2. The third reference does not render correctly in the page; but maybe this will be fine in the final guidebook:

![Screen Shot 2019-05-14 at 08 02 25](https://user-images.githubusercontent.com/12729291/57674136-a3294c80-761e-11e9-90c2-ac7ae92e9c34.png)

**Comment by davidcsterratt** [comment]
Thank-you - I should have mentioned that I know about both (1) and (2). 

If you know what the link will be I can fix (1). 

Re (2), I noticed that problem, and tried (and failed) to understand why it was happening, trying out various fixes (e.g. changing the length of the key). Nothing seemed to work. If we could see how it looks in production, that would be great.

Subject to the above, should I make a pull request?

**Comment by alex4200** [comment]
@davidcsterratt Please do so. And make sure that the notebook is put into the DEV version of the Brain Simulation Platform. See the instructions I sent earlier (https://github.com/antonelepfl/usecases/blob/dev/documentation/add_new_usecase.md)

**Comment by davidcsterratt** [comment]
I'm a bit uncertain about the files - should I refer to the files (Python notebook, Kappa and Mod files) in the *existing* collab? That's  all I can do at the moment, but I though that the notebook was being transferred to a new collab.

**Comment by alex4200** [comment]
@davidcsterratt No, the notebook is not transferred to a new Collab. Your existing notebook will be the DEV notebook. 
When the tests are done on that notebook then a COPY of that notebook will be pushed into gitlab.

When a user selects your notebook on the PRODUCTION Brain Simulation Platform, then a COPY of the github instance will be copied in the user's Collab. 

When a user selects your notebook on the DEVELOPMENT Brain Simulation Platform, then a COPY of your existing notebook will be copied in the user's Collab.

**Comment by alex4200** [comment]
@davidcsterratt  Please see the updated section in the usecase dochttps://docs.google.com/document/d/19Ni5fGFv6PTTM1D_D2FN4dj5IRhtfq1D0V2OWjXxJww/edit#heading=h.6a7rekxipfkz
I created a graph to make it more visible what is going on.

**Comment by davidcsterratt** [comment]
I've not managed to get permission to see those changes, but I've made pull requests both for the usecases and the guidebook. I'm almost certain tweaks will be needed...

**Comment by lbologna** [comment]
@alex4200, @davidcsterratt : I updated the "dev" guidebook with the new content and everything worked well at the compilation level. Here's the link:
https://lbologna.github.io/hbp-sp6-guidebook/online_usecases/subcellular_level/subcellular_level.html
Could you please check if everything is fine?

@davidcsterratt I put the introduction inside the KappaNeuron page, given that it is KappaNeuron specific and there will be other use cases. For the same reason, I suggest that the "Synaptic plasticity pathways" section is "indented" inside the main KappaNeuron section.
Maybe by prepending an "Example: " string or creating and "Example" subsection?

**Comment by alex4200** [comment]
I tested again the DEV notebook  ([HERE](https://collab.humanbrainproject.eu/#/collab/2184/nav/204920)) and it seems to work fine. David incorporated some comments. 

I think this notebook should be added to the DEV BSP.

**Comment by davidcsterratt** [comment]
That's great - thanks for your help and encouragement with this. When it's up, please let me know. It's been suggested I could do a video demo too...

**Comment by alex4200** [comment]
Hi @davidcsterratt 

the change for the usecase.json has been committed on the DEV environment, and your new usecase is online in DEV (https://collab.humanbrainproject.eu/#/collab/8444/nav/65633). I made a test run and it works fine.

I will do some user acceptance test before putting it on production.

**Comment by lbologna** [comment]
Here's the dev guidebook:
https://lbologna.github.io/hbp-sp6-guidebook/

**Comment by alex4200** [comment]
Clarification details of the documentation with @davidcsterratt

**Comment by alex4200** [comment]
Usecase and documentation in Production, closing ticket
