### ISSUE TITLE
Model Validation app uses KnowledgeGraph as database backend 

### ISSUE THREAD

**Issue by apdavison** [cnr-ibf-pa/hbp-bsp-issues#425]
Update use case

## Use Case Update
 
Aspect | Detail
------------ | -------------
Summary | Adapt the Model Validation app on the Brain Simulation Platform to use the Knowledge Graph as its database backend.
Expert | @apdavison
Deadline | end of April 2019 
Dependencies | #380
 
## List of additional/changed features 
* When using the Model Validation app and the Python client, the data is used from the KnowledgeGraph. This is the companion to #380. That ticket focuses on models, this one on validation tests and validation results.

### Tasks

- [x] develop KG metadata schemas for model projects and model instances.
- [x] develop script to migrate model catalog from PostgreSQL to KG
- [x]  adapt REST API implementation to read/write from KG instead of PostgreSQL
- [x]  thoroughly test, using KG integration server ("nexus-int")
- [x]  perform definitive migration to KG production server, deploy new REST API implementation in production

## Acceptance Criteria
* Nothing should change for the user; should still be able to use the validation framework as before.

**Comment by apdavison** [comment]
Due to pressure from reviewers to make models available through Knowledge Graph search, we changed the order of work items, and have performed a migration of model catalog data to the production KG.
This has delayed testing of the reimplementation of the REST API, which is now ongoing. New deadline for full deployment to production end of June 2019.

**Comment by apdavison** [comment]
Update: 
- re-implementation of REST API using KG backend is now deployed to a test server at https://validation-dev.humanbrainproject.eu
- All the unit tests of the VF Python client pass with this new server
- There are still a few bugs to make the Model Catalog app work with the new server
- All models already migrated to KG
- Definitive migration of validation tests and results to KG planned for this week
- Testing of online use cases against the new server in progress

**Comment by appukuttan-shailesh** [comment]
Knowledge Graph Search
https://collab.humanbrainproject.eu/#/collab/47/nav/86751

**Comment by appukuttan-shailesh** [comment]
@clupascu :
Existing REST API: https://hbp-validation-framework-api.readthedocs.io
Python Client: https://hbp-validation-client.readthedocs.io

**Comment by alex4200** [comment]
@appukuttan-shailesh 

When I use the Knowledge Graph Search and I search for the keyword 'cerebellum' I find 5 models. When I then click on `Data download: download all related data as ZIP` a new tab opens with an error
`Oops, an error occurred
This exception has been logged with id 7ca9efhig`.

Also, when I open a different model (e.g. search for 'hippocampus') I do not see a download link, but a link 'Go to the data'. 

Why does this happen? Are these bugs, or is something still missing?

**Comment by appukuttan-shailesh** [comment]
@alex4200 : I won't be the right person to answer KG related queries (at least, not yet :p). Maybe better to redirect these to @apdavison for the time being.

Regarding the "Go to the data" bit.... this must be because the model owner decided to provide a URL to Github repository containing the model (instead of a directly downloadable file URL) and your are therefore being redirected to this repository.

@apdavison : in the case of github URLs we should enforce that they point to a specific commit ID (or similar) to ensure that the model instance does not change with new commits to the repository.

**Comment by apdavison** [comment]
@alex4200 we should perhaps move this discussion to a new ticket, since your question is about the KG Search and not about the Model Validation app.

The "download as ZIP" error is indeed a bug, thanks for alerting us to this. @appukuttan-shailesh is correct that the "Go to the data" link appears when the model is on Github or ModelDB, rather than in CSCS storage.

@appukuttan-shailesh I see your point. The model instance does contain the commit ID (as the "version" attribute"), but the user could be misled if they look at the code in "master" rather than at the specific commit.

**Comment by alex4200** [comment]
@apdavison @appukuttan-shailesh  The download issue seems to be solved.

**Comment by appukuttan-shailesh** [comment]
Final task expected to be completed by end-Nov.

**Comment by alex4200** [comment]
Andrew will move the KG-based apps from staging to production in first week on January.

**Comment by apdavison** [comment]
Done
