### ISSUE TITLE
NEST-Desktop

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#458]
## New Use Case
  
Aspect | Detail
------------ | -------------
Summary | Web-based tool aimed at students to simulate small circuits with NEST, which runs as a service. 
Usecase Group | Small Circuits?
Expert | Benjamin Weyers
Scientific User | 
Deadline | end of SGA2 (March 2020) (Prototype in autumn)
Target audience | students, early adaptors
Target interface | Web GUI
HPC Requirements | None
Dependencies | 
Nominal runtime |
  
**Remove anything that does not apply**
## List of features

* Financed by HPC vouchers
* Not suitable for large models (like the SP6 models), but maybe for SGA3

*What does your use case do? 

- Interactive construction of the neuronal network
- fast simulation from local/remoted server
- learning & teaching of computational neuroscience
- no programming skills required

What activities can users perform while using it? 

Analyze spike activities or recordables from neurons (e.g. Membrane potentials). The major goal is to support students in learning computational neuroscience. NEST Dekstop is a tool deployed and ready to use in EBRAINS: https://nest-desktop.apps.hbp.eu

What makes it different from similar use cases? 

- VIOLA: Only visualization of spiking data
- NESTInstrumentationApp: Less parameterization options
- Focus on constructional teaching

 
### Tasks
 
- [ ] Optimize usability of GUI
- [ ] Topology interface (similar to NESTInstrumentationApp)
- [ ] Animation of activity (similar to VIOLA)
- [ ] NEST Desktop and NEST Server packages available on PyPI.
- [ ] NEST Desktop container available on Docker hub.
- [ ] Integration into HBP infrastructure (CSCS)
- [ ] Documentation on ReadTheDocs
- [ ] NEST Desktop in Software Catalog in Collab
- [ ] Restriction for simulation to avoid high workload of the server
    
## Acceptance Criteria
*Define here the acceptance tests to evaluate the use case’s compliance with the requirements as defined above. Also possible end users for testing can be included here.*
  
### System

- Ubuntu 18.04, Docker
- Minimal hardware requirements:
    1 CPU (single core), 4 GB RAM
- Optimal hardware requirements:
    CPU (4 cores), 12/16 GB RAM
  
### Performance

Depending on network size, simulation time and resolution of the recordings, it is pretty fast (< 5s).

**Comment by alex4200** [comment]
@bweyers  Do you have any update on this task?

**Comment by alex4200** [comment]
Update from @bweyers : Sebastian Spreizer (main developer from NEST) is working on this task.

**Comment by bweyers** [comment]
What does your use case do? 
- Interactive construction of the neuronal network
- fast simulation from local/remoted server
- learning & teaching of computational neuroscience
- no programming skills required

What activities can users perform while using it? 
Analyze spike activities or recordables from neurons (e.g. Membrane potentials). The major goal is to support students in learning computational neuroscience. NEST Dekstop is a tool deployed and ready to use in EBRAINS: https://nest-desktop.apps.hbp.eu 

What makes it different from similar use cases? 
- VIOLA: Only visualization of spiking data
- NESTInstrumentationApp: Less parameterization options
- Focus on constructional teaching

List the main functions that you will build into your product here. 
- Deployment and Session Management for NEST Desktop in FENIX/ICEI/CSCS
- Integration of features provided by VIOLA & NESTInstrumentationApp elements
- Documentation (e.g. ReadTheDocs, https://nest-desktop.readthedocs.io/)

Also specify the priority ‘mandatory’, ‘important, ‘nice to have’.
Tasks
[+] Optimize usability of GUI
[+] Topology interface (similar to NESTInstrumentationApp)
[+] Animation of activity (similar to VIOLA)
[+] NEST Desktop and NEST Server packages available on PyPI.
[+] NEST Desktop container available on Docker hub.
[+] Integration into HBP infrastructure (CSCS)
[+] Documentation on ReadTheDocs
[+] NEST Desktop in Software Catalog in Collab
[+] Restriction for simulation to avoid high workload of the server

Extra Requirements
System
Does this use case require any special system requirements (any special software package)? Does this use case require HPC access? If so, which ones? List detailed system requirements here.
System requirements: 
Ubuntu 18.04, Docker
-------------------------------------
Minimal hardware requirements:
1 CPU (single core), 4 GB RAM
Optimal hardware requirements:
CPU (4 cores), 12/16 GB RAM
Maximal hardware requirements:
- Cluster/Supercomputer?
-----------------------------------------

Performance
What are additional performance requirements for this use case? What time should it take to run from start to end?
Depending on network size, simulation time and resolution of the recordings, it is pretty fast (< 5s).

**Comment by bweyers** [comment]
Please check out the running version of NEST Desktop here: https://nest-desktop.apps.hbp.eu 
It offers various neural network models, which can be directly run. Addtionally, you can use the interactive UI to create your own examples.

**Comment by alex4200** [comment]
@bweyers I suggest to have a skype call so you explain me how to use that tool.

**Comment by bweyers** [comment]
@alex4200 Sure! There is also documentation available here: https://nest-desktop.readthedocs.io/

**Comment by alex4200** [comment]
@bweyers Ah yes that was useful. Ideally that link to the documentation is included somehow as a static link in the application itself, but anyways it should be part of the guidebook. 

But now I was able to create even a small network, simulate it and get some results.

**Comment by bweyers** [comment]
@alex4200 Now me question is what are should be next steps? There is a list of aspect, which will be changed over the next weeks and month as NEST Desktop will be part of the core project.

**Comment by alex4200** [comment]
@bweyers I would say the next steps are:

1. Check the boxes in the original description, i.e. to mark what has been done, and to see what still needs to be done. 
2. Get in the documentation (see documentation section in the [UseCases Document](https://docs.google.com/document/d/19Ni5fGFv6PTTM1D_D2FN4dj5IRhtfq1D0V2OWjXxJww/edit#heading=h.nhjbi1r62493) )
3. Add it as a new usecase to the Brain Simulation Platform (see [HERE](https://github.com/antonelepfl/usecases/blob/dev/documentation/add_new_usecase.md) how to do it).

**Comment by alex4200** [comment]
@bweyers Any news on this issue?

**Comment by bweyers** [comment]
We are currently on the way to prepare the material for the documentation refering to the list above. Let you know when we are ready to open the pull requests.

**Comment by alex4200** [comment]
@bweyers Hi Benjamin, do you have any update on that remaining task?

**Comment by bweyers** [comment]
@alex4200 I finished a description of the use case and would now create a pull request for the content you find here: https://docs.google.com/document/d/1SOhrEVj8b65UffMD-WGjsME8pFXGmghAspBgbafjIZM/edit?usp=sharing

**Comment by bweyers** [comment]
@alex4200 just created a pull request for including the use case into the guidebook.

**Comment by lbologna** [comment]
Hello @bweyers and @alex4200,

I just accepted the pull request for the documentation. 
Here's the link in DEV:
https://lbologna.github.io/hbp-sp6-guidebook/online_usecases/subcellular_level/NESTDesktop/NESTDesktop.html

Thanks @bweyers for not inserting the page in the toc at the moment. I suggest we keep it like this until the use case is ready in the BSP.

Do you already know in which Use Case group the use case will go? At the moment it is in the "Subcellular Level" but maybe it would be more appropriate to move it to "Small circuit" or "Brain area" in silico experiments?

**Comment by bweyers** [comment]
@lbologna Thanks for accepting the pull request. Small circuit is also fine. However, NEST Desktop in actually a tool aka graphical user interface for NEST simulator running in the web. It has a slight focus on eduction as potetial use scenarios. It might be also possible to have a new category? I would support to not creating a new one... 

Thus, we will not need a notebook. Should I add the JSON still into the place it should go? Need to look it up again...

**Comment by alex4200** [comment]
Hi,


I just found one small typo at the end of the documentation:


To get an overview of how to use it, please have a look at the QuickStart Section of NEST Dekstop’s documentation


Cheers

Alex

________________________________

**Comment by bweyers** [comment]
@alex4200 Thanks! I fixed it locally but will wait with the pull request until we have all further changes needed integrated.

**Comment by bweyers** [comment]
@lbologna There are still some questions I have. I would very much appreciate if you could have a look at them and send me an answer: https://github.com/cnr-ibf-pa/hbp-bsp-issues/issues/458#issuecomment-624543876

**Comment by lbologna** [comment]
Hello @bweyers,

I discussed together with @mmigliore about where to position the NEST-Desktop web app, and given that it will be a Use Case running on a standalone platform, we believe it would be suitable in this case to create a new item named "NEST Desktop" which will redirect the user to the NEST Desktop web server (https://nest-desktop.apps.hbp.eu/#/).

This could be put in the Online Use Cases menu, below the Highly Integrated Workflows.

If it's fine with you,  I can add a Markdown/External link on the BSP. In the meantime, could you please create a new paragraph in the Guidebook (called "NEST Desktop") just below the "Highly Integrated Workflows" and move the NEST page there? 
Thank you.

**Comment by bweyers** [comment]
Hi @lbologna,
Hi @mmigliore., 

I am wondering whether there is the chance to rename the category? The description provided seems reasonable for NEST Desktop but I would assume that one would not assume to find NEST Desktop under "Highly Integrated Workflows" as NEST Desktop is not a tool for workflow modeling/implementation or does not implement a workflow. What about "brain modelling tools" as mentioned in the description or anything else which might be better pointing to the aspect that standalone tools are listed here adding to the BSP?

Thanks, 

Benni

**Comment by lbologna** [comment]
Hello @bweyers,

our suggestion is to put "NEST Desktop" at the same level of the other Use Case groups (for example below (or above) the "Highly Integrated Workflows", not under/inside that group).
This will not hide its visibility and will not create misunderstandings in that the name "NEST Desktop" should well identify it as a standalone application.

**Comment by bweyers** [comment]
Hi @lbologna 
Oh that is great then! That would make sense :) Sorry for the misunderstanding. 

That is fine with me. I will do the adaption in the reposirtory and create a pull request.

**Comment by bweyers** [comment]
@lbologna I just created the pull request. Let me know if there is anything else I need to do.

**Comment by alex4200** [comment]
Use case online as well documentation. 

Closing ticket
