### ISSUE TITLE
New Live Paper Bruce et al 2019

### ISSUE THREAD

**Issue by lbologna** [cnr-ibf-pa/hbp-bsp-issues#462]
## New Live Paper Bruce et al 2019

Dev link:
https://cnr-ibf-pa.github.io/hbp-bsp-live-papers-dev/2019/bruce_et_al_2019/bruce_et_al_2019.html

Aspect | Detail
------------ | -------------
Summary | New Live Paper Bruce et al 2019
Expert |  @lbologna @njbruce 
Deadline | M18
Dependencies | None
 
## List of additional/changed features 
New Live Paper inserted.

### Tasks

- [x] Build Live Paper and generate pull request (@njbruce )
- [x] Accept pull request, check formatting, correct code errors (@lbologna )
- [x] Check that everything works (@alex4200 )
- [x] Put to production (@lbologna )

## Acceptance Criteria
The Live Paper is correctly visible and all links work

**Comment by lbologna** [comment]
Hello,

@njbruce I accepted the pull request for your live paper and checked the formatting and everything looked very good to me. I inserted the "Authors" tag which was missing, modified the links so that they open in a new tab and re-aligned a couple of "Download" links. 
As for the Collab, in order to be consistent with the other live papers, you should please remove the first item (which is a "Link" and only allows to open the page in a different tab) and replace it with a "Markdown" item by choosing "Content from an external source" for the "Overview Source". This will allow the paper to be displayed inside the Collab

@alex4200 could you please check that everything works well before moving to production?

Thank you

**Comment by alex4200** [comment]
@lbologna A link to the DEV version of the live paper would be good to have ... (I suggest to add it in the main description).

**Comment by lbologna** [comment]
> @lbologna A link to the DEV version of the live paper would be good to have ... (I suggest to add it in the main description).

@alex4200 sure, sorry I forgot to add it. I put it in the main description.

**Comment by alex4200** [comment]
I made a check that all links do work, and that the links lead to where they should lead in separate windows, and that I can download files, and the 3D viewers. it all seems to work fine. 

I checked the checkbox above.

**Comment by lbologna** [comment]
Thanks @alex4200!
Moved to production
Closing the ticket
