### ISSUE TITLE
New Live Paper Kokh et al. 2019

### ISSUE THREAD

**Issue by lbologna** [cnr-ibf-pa/hbp-bsp-issues#466]
## New Live Paper Kokh et al 2019

Dev link:
https://cnr-ibf-pa.github.io/hbp-bsp-live-papers-dev/2019/kokh_et_al_2019/kokh_et_al_2019.html

Aspect | Detail
------------ | -------------
Summary | New Live Paper Bruce et al 2019
Expert |  @lbologna @DKokh 
Deadline | M18
Dependencies | None
 
## List of additional/changed features 
New Live Paper inserted.

### Tasks

- [x] Build Live Paper and generate pull request (@DKokh  )
- [x] Accept pull request, check formatting, correct code errors (@lbologna )
- [ ] Check that everything works (@alex4200, @DKokh )
- [ ] Put to production (@lbologna )

## Acceptance Criteria
The Live Paper is correctly visible and all links work

**Comment by lbologna** [comment]
Hello,

@alex4200, @DKokh I uploaded to 'dev' the live paper Daria has been preparing. I corrected some error with the layout, mostly for alignment problems. Could you please have a look and see if this is fine with you?

@DKokh have you already created a Collab to be linked to this Live Paper? If not, I can do it and set the content as we have done for the other LPs. Also, at the bottom left of the page there is a link named "Imprint/Privacy" that redirects to one of the HITS pages. If this has to be read by the users I suggest to move it to a different place (maybe closer to the data it refers to?!).

Thank you

**Comment by DKokh** [comment]
I fixed some typos and removed a link to HITS page.  
@lbologna : no, I don't have any Collab linked to this paper. If it is required, please do this.
Thanks!

**Comment by alex4200** [comment]
@lbologna @DKokh Upon looking at the live paper I have the following comments:

- When I open the 'Models' and look at the first tab, an image is missing:
  ![Selection_795](https://user-images.githubusercontent.com/12729291/64504652-efd11b80-d2d0-11e9-8885-52a9096f3d49.png)
- When I open 'Source code and data archive' I see a 'download' button, but it is not a download button. It just seems to lead to the zendo webpage (in the same tab!). 

Otherwise of that all seems to work (links, downloads, 3D images) and the spelling also seems to be ok.

**Comment by DKokh** [comment]
@DKokh @lbologna :   The figure was corrected in a revised version. It is in a new pull request
https://github.com/cnr-ibf-pa/hbp-bsp-live-papers-dev/pulls. The codes can be downloaded from  zenodo webpage . I guess that the download button is appropriate here. Or should I change to something else ? 
Thank a lot!

**Comment by alex4200** [comment]
@DKokh I am just saying that when I click on a 'download' button, I expect the download of something to begin immediately. But in the current case the click on the 'download' button does no start a download - it opens another webpage. Maybe instead of writing 'download' it is better to write 'open' (as the user opens a new page).

**Comment by DKokh** [comment]
@lbologna   ok, thanks for the idea, I'll correct this and push an updated version asap

**Comment by lbologna** [comment]
Hello,
I modified the button's name as suggested by @alex4200 and moved to production.
If everything looks fine to you, we can close the ticket.
Thanks

**Comment by alex4200** [comment]
Yes is fine with me
