### ISSUE TITLE
Python3 update for notebooks

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#476]
## Use Case Update
 
Aspect | Detail
------------ | -------------
Summary | As python2 gets deprecated by the end of the year, the notebooks in the brain simulation platform should be running a python3 kernel. This requires some adjustment for some notebooks.
HowTo | You change the kernel to 'python3' in the notebook, and then you save it (and fix broken items). 
Deadline | 31.1.2020
 
### Tasks

- [ ] unknown: Molecular: Brownian dynamics simulation - analysis: Value Error in Cell 8
- [ ] unknown: Molecular: Calculate the electrostatic potential of a protein from its atomic structure: No module named 'clusterpipsa'
- [ ] @davidcsterratt: Subcellular: KappaNEURON Ca Pump: No matching distribution found for KappaNEURON==0.3.2
- [ ] @clupascu: Usecases Synaptic Events Fitting
- [ ] @clupascu: Usecases (Re)build single hippocampal cell
- [ ] @SteMasoli: Usecases in Single Cell Building
- [ ] @a1eko: Optimite FS interneuron use case
- [x] @jdcourcol: Cell Placement - Hippocampus
- [x] @SelezioneCasuale: Usecases Cerebellum (in Circuit Building)
- [x] @jdcourcol: Morphology Analysis usecase
- [ ] @elisamarenzi: Cerebellum microcircuit
- [x] @appukuttan-shailesh: Validation usecases

## Acceptance Criteria
*Notebook has changed to python3 kernel and runs as before with python2

**Comment by appukuttan-shailesh** [comment]
Inside a Jupyter notebook in a Collab, I have the single statement:
`from neuron import h`
or
`import neuron`
This works fine when using "Python 2" kernel. But when I set it to "Python 3", I get the following error:

> Traceback (most recent call last):
> 
>  File "/opt/conda/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2862, in run_code
>    exec(code_obj, self.user_global_ns, self.user_ns)
>  File "<ipython-input-3-323dccb06f43>", line 1, in <module>
>    from neuron import h
>  File "/home/jovyan/.local/nrn/lib/python/neuron/__init__.py", line 120
>    print "Enabling NEURON+Python help system."
>                                              ^
> SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Enabling NEURON+Python help system.")?

@sasaray , @apdavison have also reported coming across this issue on the Collaboratory.
Do others also face this? Any why does it arise? My impression is that NEURON is compatible with Python3, then why this issue?

**Comment by antonelepfl** [comment]
https://support.humanbrainproject.eu/#ticket/zoom/2295
https://support.humanbrainproject.eu/#ticket/zoom/2262

**Comment by alex4200** [comment]
Response from support:

```
both Neuron 7.4 and Neuron 7.6 are installed in the Collaboratory. The 7.6 version is compatible with Python 3 and can be switched to using the instructions here: 
https://collab.humanbrainproject.eu/#/collab/509/nav/327793
```

**Comment by clupascu** [comment]
yes. But as I replied to support, we still have the problem that Neuron 7.6 is not compatible with BluePyOpt used for optimizing single cells, so most of the usecases running BluePyOpt will not work...

**Comment by alex4200** [comment]
@Carmen What ticket are you referring to?

**Comment by clupascu** [comment]
I am referring to this ticket https://support.humanbrainproject.eu/#ticket/zoom/2295

**Comment by SteMasoli** [comment]
I'm testing a python 3 version of the granule cell axon usecase but:

```
!pip3 install "hbp-service-client" >/dev/null

storage = get_bbp_client().document 

NameError: name 'get_bbp_client' is not defined
```

It works under python 2.

**Comment by alex4200** [comment]
@SteMasoli  I can reproduce that behavior. I opened a bug report with the collab team, I will keep you updated.

**Comment by alex4200** [comment]
@SteMasoli Any interaction with the storage must be done using the  hbp_client. You can find documentation [HERE](https://collab.humanbrainproject.eu/#/collab/509/nav/24072). If you have any issues, please contact the collaboratory support at support@humanbrainproject.eu.

**Comment by SteMasoli** [comment]
> You can find documentation HERE. 

Thanks for the link to the documentation. 
I had to rebuild the way i was accessing the file to make it work right.

I have followed the procedure to switch to NEURON 7.6 but, in conjunction with BluePyOpt, it does not work.

After this:
`nrn = ephys.simulators.NrnSimulator()`
It says:
`hoc shared library not found in /home/jovyan/.local/nrn/lib/python/neuron`

```
`!ls -la /home/jovyan/.local/`

drwxr-xr-x  2 jovyan users 4096 Aug 23 09:27 bin

drwxr-xr-x  3 jovyan users 4096 Aug 23 09:20 include

drwxr-xr-x  4 jovyan users 4096 Aug 23 09:27 lib

lrwxrwxrwx  1 jovyan users   28 Oct 23 15:25 nrn -> /home/jovyan/.local/nrn-7.6/

drwxr-xr-x  7 jovyan users 4096 Oct 23 15:25 nrn-7.6

drwxr-xr-x  5 jovyan users 4096 Sep  1 19:22 share`
```

Fun fact, i have no problem compiling the MOD files.

**Comment by clupascu** [comment]
I tested NEURON 7.6 and BluePyOpt this week. It worked for me. I cannot test it again now as I have a kernel error in my notebooks. I will test it again after the JupyterHub maintenance from tomorrow.

**Comment by SteMasoli** [comment]
Yestarday was running fine and now i have a completely new issue with "hbp-service-client 1.1.1".

```
!pip3 install --upgrade "hbp-service-client==1.1.1" >/dev/null
clients = get_hbp_service_client()
```

`RuntimeError                              Traceback (most recent call last)
<ipython-input-8-2df61c6fceeb> in <module>
      1 import os
----> 2 clients = get_hbp_service_client()


<ipython-input-1-889819196c7f> in get_hbp_service_client()
      3 HBPClient.CURRENT_COLLAB_ID = 3834;
      4 def get_hbp_service_client():
----> 5     return HBPClient.new(oauth.get_token(), 'prod');
      6 def get_collab_storage_path():
      7     client = get_hbp_service_client()

/opt/conda/lib/python3.6/site-packages/jupyter_collab_storage/oauth_token_handler.py in get_token()
     68                       body=urlencode(params))
     69 
---> 70     http_client = HTTPClient()
     71     try:
     72         resp = http_client.fetch(req)

/opt/conda/lib/python3.6/site-packages/tornado/httpclient.py in __init__(self, async_client_class, **kwargs)
    105             return async_client_class(**kwargs)
    106 
--> 107         self._async_client = self._io_loop.run_sync(make_client)
    108         self._closed = False
    109 

/opt/conda/lib/python3.6/site-packages/tornado/ioloop.py in run_sync(self, func, timeout)
    524 
    525             timeout_handle = self.add_timeout(self.time() + timeout, timeout_callback)
--> 526         self.start()
    527         if timeout is not None:
    528             self.remove_timeout(timeout_handle)

/opt/conda/lib/python3.6/site-packages/tornado/platform/asyncio.py in start(self)
    146             self._setup_logging()
    147             asyncio.set_event_loop(self.asyncio_loop)
--> 148             self.asyncio_loop.run_forever()
    149         finally:
    150             asyncio.set_event_loop(old_loop)

/opt/conda/lib/python3.6/asyncio/base_events.py in run_forever(self)
    415         if events._get_running_loop() is not None:
    416             raise RuntimeError(
--> 417                 'Cannot run the event loop while another loop is running')
    418         self._set_coroutine_wrapper(self._debug)
    419         self._thread_id = threading.get_ident()

RuntimeError: Cannot run the event loop while another loop is running`

**Comment by SteMasoli** [comment]
Except for the previous issue, the usecase i'm testing runs perfectly till the end with the latest BluePyOpt and Neuron7.6

**Comment by alex4200** [comment]
@SteMasoli Can you please try the following:

1. Split the two commands in two separate cells. 
2. Then run the both. 
3. If you get the same error do a 'kernel-reload' and run the second cell alone again. 

And report what output you now get.

**Comment by SteMasoli** [comment]
@alex4200 
Sorry for the delay. I had an issue accessing any type of notebook from my account. After a reset i have access again.

Splitting the code into:
`!pip3 install --upgrade "hbp-service-client==1.1.1" >/dev/null`

and 
`clients = get_hbp_service_client()`

generates a different error.

`ImportError                               Traceback (most recent call last)
<ipython-input-6-94c833aa5292> in <module>()
----> 1 clients = get_hbp_service_client()

<ipython-input-1-815aa1d0632c> in get_hbp_service_client()
      3 HBPClient.CURRENT_COLLAB_ID = 3834;
      4 def get_hbp_service_client():
----> 5     return HBPClient.new(oauth.get_token(), 'prod');
      6 def get_collab_storage_path():
      7     client = get_hbp_service_client()

/opt/conda/lib/python3.6/site-packages/jupyter_collab_storage/oauth_token_handler.py in get_token()
     68                       body=urlencode(params))
     69 
---> 70     http_client = HTTPClient()
     71     try:
     72         resp = http_client.fetch(req)

/opt/conda/lib/python3.6/site-packages/tornado/httpclient.py in __init__(self, async_client_class, **kwargs)
     76         except Exception as e:
     77             # Other errors are possible, such as IOError.
---> 78             print("Error: " + str(e))
     79         http_client.close()
     80 

/opt/conda/lib/python3.6/site-packages/tornado/httpclient.py in __new__(cls, io_loop, force_instance, **kwargs)
    166         AsyncHTTPClient.configure(
    167             None, defaults=dict(user_agent="MyUserAgent"))
--> 168         # or with force_instance:
    169         client = AsyncHTTPClient(force_instance=True,
    170             defaults=dict(user_agent="MyUserAgent"))

/opt/conda/lib/python3.6/site-packages/tornado/util.py in __new__(cls, *args, **kwargs)
    281             return impl(*args, **init_kwargs)
    282         instance = super(Configurable, cls).__new__(impl)
--> 283         # initialize vs __init__ chosen for compatibility with AsyncHTTPClient
    284         # singleton magic.  If we get rid of that we can switch to __init__
    285         # here too.

/opt/conda/lib/python3.6/site-packages/tornado/util.py in configured_class(cls)
    345             base.__impl_class = cls.configurable_default()
    346         if base.__impl_class is not None:
--> 347             return base.__impl_class
    348         else:
    349             # Should be impossible, but mypy wants an explicit check.

/opt/conda/lib/python3.6/site-packages/tornado/httpclient.py in configurable_default(cls)
    147             except Exception as e:
    148                 print("Error: %s" % e)
--> 149             else:
    150                 print(response.body)
    151 

/opt/conda/lib/python3.6/site-packages/tornado/simple_httpclient.py in <module>()
     20 )
     21 from tornado.log import gen_log
---> 22 from tornado.tcpclient import TCPClient
     23 
     24 import base64

/opt/conda/lib/python3.6/site-packages/tornado/tcpclient.py in <module>()
     23 import ssl
     24 
---> 25 from tornado.concurrent import Future, future_add_done_callback
     26 from tornado.ioloop import IOLoop
     27 from tornado.iostream import IOStream

ImportError: cannot import name 'future_add_done_callback'`

**Comment by alex4200** [comment]
@SteMasoli Have you reloaded the kernel after you installed the updated version of  `hbp-service-client==1.1.1`?

**Comment by SteMasoli** [comment]
@alex4200 
yes i have. 

There is something going on with my account. I cannot access notebooks for the second time in 3 days.

**Comment by alex4200** [comment]
@SteMasoli  What is the error you get? Can you make a screenshot? I would write to support@humanbrainproject.eu

**Comment by SteMasoli** [comment]
@alex4200 
I'm in contact with support. 
The previous breaking of my environment was caused by the Tornado package which cannot be the most recent.

Since the reset i have upgrade again the hbp-service-client to 1.1.1, which uses Tornado and this combination killed, again, my ability to load the notebooks.

I have requested another reset of my environment and I'll try to use the basic version (1.0) of the "hbp-service-client". Incidentally, until 25 October, everything was running fine.

**Comment by SteMasoli** [comment]
With Tornado 4.5.3 and "hbp-service-client" 1.0.0
"StorageForbiddenException: You are forbidden to do this."

With Tornado 6.0 and hbp-service-client 1.0.0/1.1.1
"ImportError: cannot import name 'future_add_done_callback'`"

If i do an upgrade to hbp-service-client 1.1.1, with Tornado 6.0, it collapse the collab...

The hbp-service-client is compatible with Python3?

**Comment by SteMasoli** [comment]
@alex4200  After some more tinkering i have found a combination of packets that are good enough to run the usecase without braking the collab.

**Comment by alex4200** [comment]
@SteMasoli That is good to hear. Please provide the package/version combination that finally works for you - maybe that is helpful for other people as well.

**Comment by clupascu** [comment]
The Synaptic events fitting usecases (https://collab.humanbrainproject.eu/#/collab/71255/nav/483240) are now compatible with Python 3.

@alex4200 can you please test if everything works fine?

**Comment by alex4200** [comment]
@clupascu Thanks for that - I had a look and started a job on Jureca with "Synaptic events fitting". But when the job was SUCCESSFUL I saw the following error:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-13-28acce706607> in checksimunicore(CheckSU)
     53                 content = get_file_content(wd+"/files"+file_path,auth)
     54                 with open(f,"w") as local_file:
---> 55                     local_file.write(content)
     56                 clients.storage.upload_file(str(f),str(os.path.join(storeto,f)),filetype)
     57         STU.layout.display='none'

TypeError: write() argument must be str, not bytes

Maybe you have to open the file in binary mode (like `open(f,"wb")` )?

**Comment by clupascu** [comment]
@alex4200 can you please try again? I modified the notebooks.

**Comment by alex4200** [comment]
@clupascu  Is that problem also fixed in the analysis notebook?

**Comment by clupascu** [comment]
@alex4200 the problem shouldn't be in the analysis notebook. Please let me know if you find the same problem in the analysis notebook while running the automatic tests.

**Comment by alex4200** [comment]
@clupascu I see two issues currently: 

1. With the notebook "Synaptic events fitting":
I choose NIP data (for example "sIPSCs from juvenile (P21-30) C57BL/6J male mice hippocampus CA1 pyramidal cell (A3)") and start it on Marconi (account HBP_CDP2_it_0) But the job always fails - on Marconi it says in the stderr (e.g. for job 691c715f-32a0-4e98-8612-116edef8e64c):

```
slurmstepd: error: *** JOB 5871304 ON r065c01s02 CANCELLED AT 2019-12-05T15:35:50 DUE TO TIME LIMIT ***
slurmstepd: error: *** STEP 5871304.0 ON r065c01s02 CANCELLED AT 2019-12-05T15:35:50 DUE TO TIME LIMIT ***
```

2. Within the notebook "Synaptic events fitting with analysis"
Here I select "View simulations -> HPC -> Jureca" and click on "View simulations". 
After the simulations have been loaded I click on 'Move" of the mast entry (see screenshot), where I get the following error:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-12-872208fcd0a5> in movetostorage(job_url, name, BT)
     60                     content = get_file_content(wd+"/files"+file_path,auth)
     61                     with open(f,"w") as local_file:
---> 62                         local_file.write(content)
     63                     clients.storage.upload_file(str(f),str(os.path.join(storeto,f)),filetype)
     64             BT.disabled=True

TypeError: write() argument must be str, not bytes
```

![Selection_925](https://user-images.githubusercontent.com/12729291/70249504-bfd4cf80-177c-11ea-8def-4eb06b3c0ef2.png)

**Comment by clupascu** [comment]
@alex4200 I fixed the second issue. For the first one I have to see what happens on Marconi. I hope that modules are still working on Marconi. I will check this and let you know.

**Comment by alex4200** [comment]
@clupascu Found some other problem when clicking on "Best Fit" in the Analysis notebook for the example:

![Selection_927](https://user-images.githubusercontent.com/12729291/70305005-84c9af00-1803-11ea-86f2-cc6b050b3c9c.png)

It looks like `nrn` points to neuron-7.4. With neuron-7.6 the error is not present anymore. 

I suggest to include these two lines in every notebook that uses neuron, just to make sure the correct 7.6 version is being used:

```
!rm -f /home/jovyan/.local/nrn
!ln -s /home/jovyan/.local/nrn-7.6 /home/jovyan/.local/nrn
```

**Comment by clupascu** [comment]
@alex4200 I fixed this. Thank you for your suggestion.

**Comment by appukuttan-shailesh** [comment]
Validation usecases have been made Py3 compatible. Support for Py2 has been dropped.

**Comment by clupascu** [comment]
@alex4200 For this issue on Marconi you selected the "demo" version or the "all_traces" version? Can you point me to the stdout and stderr you get? 

>     1. With the notebook "Synaptic events fitting":
>        I choose NIP data (for example "sIPSCs from juvenile (P21-30) C57BL/6J male mice     
>      hippocampus CA1 pyramidal cell (A3)") and start it on Marconi (account HBP_CDP2_it_0) But 
>      the job always fails - on Marconi it says in the stderr (e.g. for job 691c715f-
>      32a0-4e98-8612-116edef8e64c):
>      slurmstepd: error: *** JOB 5871304 ON r065c01s02 CANCELLED AT 2019-12-05T15:35:50  
>      DUE TO TIME LIMIT ***
>      slurmstepd: error: *** STEP 5871304.0 ON r065c01s02 CANCELLED AT 2019-12-05T15:35:50 >      DUE TO TIME LIMIT ***

**Comment by alex4200** [comment]
@clupascu I just repeated that issue, and I did select 'demo' now (it was 'all traces' before). But now I do not even get any output log. Nothing. No change in the folder on Marconi (39917b26-bb5c-4681-91f5-c3b747497dfc):

```
total 3072
-rw------- 1 adietz00 interactive     953 Dec 12 13:18 configA3.txt
-rw------- 1 adietz00 interactive 1255425 Dec 12 13:18 expA3.txt
-rw------- 1 adietz00 interactive    1170 Dec 12 13:18 cellprop.py
-rw------- 1 adietz00 interactive    9275 Dec 12 13:18 fitting.py
-rw------- 1 adietz00 interactive    9100 Dec 12 13:18 fitness.py
-rw------- 1 adietz00 interactive    1982 Dec 12 13:18 readconffile.py
-rw------- 1 adietz00 interactive    1825 Dec 12 13:18 readexpfile.py
-rw------- 1 adietz00 interactive    3829 Dec 12 13:18 netstims.mod
-rw------- 1 adietz00 interactive   10831 Dec 12 13:18 ProbGABAAB_EMS_GEPH_g.mod
-rwxr-xr-x 1 adietz00 interactive     363 Dec 12 13:18 prepare.sh
-rwxr-xr-x 1 adietz00 interactive     386 Dec 12 13:18 run2.sh
-rwxr-xr-x 1 adietz00 interactive     386 Dec 12 13:18 run3.sh
drwxr-xr-x 3 adietz00 interactive    4096 Dec 12 13:18 x86_64
```

When I run the command from `run2.sh` manually it works, I get results. But I see a warning when loading the `numpy` module:

```
WARNING: python/3.6.4 cannot be loaded due to a conflict.
HINT: Might try "module unload python" first.
```

Maybe that has something to do with the failed job?

**Comment by clupascu** [comment]
@alex4200 It is strange. I get the output log and I see in the stderr the same warning as above.
I have to ask if the Neuron version (NEURON -- VERSION 7.5 master (9fc7197) 2017-11-06) used on Marconi is Python 3.5 compatible. 

It seems that when I load the modules

module purge
module load autoload intelmpi
module load autoload python
module load autoload mkl
module load autoload numpy
export PATH=/marconi_work/HBP_CDP2_it/neuron/nrnmpi/x86_64/bin:$PATH

I get 

Currently Loaded Modulefiles:
 1) profile/base                 5) python/3.5.2
 2) autoload                     6) mkl/2018--binary
 3) intel/pe-xe-2018--binary     7) numpy/1.14.0--python--3.6.4
 4) intelmpi/2018--binary

**Comment by antonelepfl** [comment]
@alex4200 can you update the description checkboxes with the notebooks that are not python 3 yet?

**Comment by alex4200** [comment]
Individual tickets creates for the notebooks. Closing this ticket
