### ISSUE TITLE
HHNB: submit and fetch jobs to/from CSCS-DAINT service account

### ISSUE THREAD

**Issue by lbologna** [cnr-ibf-pa/hbp-bsp-issues#486]
## Single Cell Building: Hodgkin-Huxley Neuron Builder Update
 
Aspect | Detail
------------ | -------------
Summary | The Hodgkin-Huxley Neuron Builder will allow the user to submit jobs to the CSCS-DAINT HPC platform through the Service Account
Expert | @lbologna 
Deadline | 8th Nov 2019
Dependencies | None 
 
## List of additional/changed features 
The user will be provided with a new HPC system to be used for job submission, in the job submission panel of the HHNB. This newly provided choice will be for the CSCS-DAINT HPC system through the Service Account and will be of particular importance in that the user will not be required to have any credentials or to own any project on the CSCS-DAINT system for the job submission.

### Tasks

- [x] Insert the new functionalities on the DEV Platform (Frontend)
- [x] Insert the new functionalities on the DEV Platform (Backend)
- [x] Developer testing
- [x] Test user: test submission to the HPC system (CSCS-DAINT ) through the Service Account (on DEV)
- [x] Test user: test result fetching from the HPC system (CSCS-DAINT ) through the Service Account (on DEV)
- [x] Move to production (PROD)

## Acceptance Criteria
The user is able to submit a job to the CSCS-DAINT HPC system through the Service Account of the HHNB use case, fetch the results and launch the simulation without errors

**Comment by lbologna** [comment]
Implemented in DEV.

@alex4200 could you please verify that everything works well before putting to PROD?
Here's the link: https://collab.humanbrainproject.eu/#/collab/1256/nav/29703
Thank you

**Comment by alex4200** [comment]
Current status (based on discussion with Luca):
- PizDaint seems to not generate correctly the zip file
- NSG reports back "No .hoc file is present in the final simulation folder"
- Suggestion: Give the user the possibility to download whatever is being generated (to debug, investigate etc.)

**Comment by lbologna** [comment]
Hello @alex4200,
I implemented the option to download any generated output file from the remote system (even if the job failed) so that the user can read the logs (e.g. stderr, stout). In case no output is generated, the "Download results" button (in the "Optimization Results" panel) will be disabled.

Could you please have a look before moving to PROD?
Here's the link:
https://collab.humanbrainproject.eu/#/collab/1256/nav/29703

Thank you!

**Comment by lbologna** [comment]
Thanks @alex4200 for testing.
Moved HHNB to prod.

**Comment by alex4200** [comment]
Tested for PizDaint and ServiceAccount, seems to work.
