### ISSUE TITLE
Guidebook: documentation for HPC Monitor

### ISSUE THREAD

**Issue by lbologna** [cnr-ibf-pa/hbp-bsp-issues#490]
## Insert documentation in the Guidebook for the HPC monitor tool
 
Aspect | Detail
------------ | -------------
Summary | Insert Guidebook page for HPC monitor
Expert | @lbologna 
Deadline | 30 Nov 2019
Dependencies | None
 
## List of additional/changed features 
The user is provided with a dedicated page on the HPC monitor in the Guidebook, with explanations about the icon meaning and the operation she/he can perform.
Priority: ‘mandatory’

### Tasks

- [x] Insert documentation page in the Guidebook (DEV)
- [ ] Test that everything is well written and formatted
- [ ] Put into PROD

## Acceptance Criteria
The figures are correctly visualized and the text is well written and formatted

**Comment by lbologna** [comment]
Hello @alex4200,

I just added the HPC Status Monitor Page in the Guidebook. Given that this will be a standalone item in the BSP, I created an entry in the TOC at the same level as the Getting Started and the Online Use Cases ones.
Could you please check whether some corrections/changes are needed?
Here's the link:
https://lbologna.github.io/hbp-sp6-guidebook/hpc_status_monitor/hpc_status_monitor.html
Thank you!

**Comment by alex4200** [comment]
@lbologna Thanks, I think the guidebook page is fine. 

One thing, however, I overlooked before regarding the actual monitor page. Would it be possible to use a different color scheme for the User's Detail Total row (for example make the background dark grey all the time). Then the "Total" row is always distinct from the project rows and easier to spot. 

Sorry for not mentioning that earlier.

**Comment by alex4200** [comment]
Works as expected
